import {targetSize} from './balanceMetrics.js';
const $=id=>document.getElementById(id);let data,userData,loading=false,loadVersion=0;
const metrics=[['meanSize','평균 크기 · 직경'],['opportunityRate','성장 기회 노출 · %'],['crisisRate','위기 노출 · %'],['opportunityFrequency','새 성장 기회 · 개체·분당'],['crisisFrequency','새 위기 · 개체·분당'],['reward','기회 1회 평균 보상 · 직경'],['hpLoss','실제 받은 피해 · HP%/개체 표본'],['severity','위기 상대 심각도 · 0~1'],['growthRate','실제 성장 속도 · 직경/초']];
function plot(canvas,series,labels,unit){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const vals=series.flatMap(s=>s.values).filter(Number.isFinite),max=Math.max(1,...vals)*1.12,min=Math.min(0,...vals),left=58,right=w-14,top=Math.max(44,16+Math.ceil(series.length/3)*15),bottom=h-54;ctx.font='12px system-ui';ctx.fillStyle='#94a3b8';for(let i=0;i<=4;i++){const y=top+(bottom-top)*i/4,v=max-(max-min)*i/4;ctx.strokeStyle='#2b3c52';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillText(v.toFixed(max<3?2:0),4,y+4);}series.forEach((s,n)=>{ctx.strokeStyle=s.color;ctx.lineWidth=2.5;ctx.beginPath();let begun=false;s.values.forEach((v,i)=>{if(!Number.isFinite(v)){begun=false;return;}const x=left+(right-left)*i/Math.max(1,labels.length-1),y=bottom-(v-min)/(max-min)*(bottom-top);if(begun)ctx.lineTo(x,y);else ctx.moveTo(x,y);begun=true;});ctx.stroke();ctx.fillStyle=s.color;s.values.forEach((v,i)=>{if(!Number.isFinite(v))return;ctx.beginPath();ctx.arc(left+(right-left)*i/Math.max(1,labels.length-1),bottom-(v-min)/(max-min)*(bottom-top),3,0,7);ctx.fill();});ctx.fillText(s.name,60+(n%3)*245,14+Math.floor(n/3)*15);});const stride=Math.max(1,Math.ceil(labels.length/7));labels.forEach((v,i)=>{if(i%stride!==0&&i!==labels.length-1)return;ctx.save();ctx.translate(left+(right-left)*i/Math.max(1,labels.length-1),bottom+19);ctx.rotate(-.2);ctx.fillStyle='#94a3b8';ctx.fillText(String(v),-8,0);ctx.restore();});}
function aggregate(rows){const sum=(k,list=rows)=>list.reduce((s,r)=>s+(Number.isFinite(r[k])?r[k]:0),0),n=sum('samples'),opRows=rows.filter(r=>r.opportunityMeasured!==false),riskRows=rows.filter(r=>r.crisisMeasured!==false),hpRows=rows.filter(r=>r.hpMeasured!==false),opN=sum('samples',opRows),riskN=sum('samples',riskRows),hpN=sum('samples',hpRows),opp=sum('opportunities',opRows),risk=sum('crises',riskRows),exposure=list=>list.reduce((s,r)=>s+r.samples*(r.sampleSeconds??5),0);return{samples:n,meanSize:n?sum('sizeSum')/n:null,opportunityRate:opN?opp/opN*100:null,crisisRate:riskN?risk/riskN*100:null,opportunityFrequency:opN?sum('opportunityStarts',opRows)/exposure(opRows)*60:null,crisisFrequency:riskN?sum('crisisStarts',riskRows)/exposure(riskRows)*60:null,reward:opp?sum('rewardSum',opRows)/opp:null,hpLoss:hpN?sum('hpLostRatio',hpRows)/hpN*100:null,severity:risk?sum('severitySum',riskRows)/risk:null,growthRate:sum('elapsed')?sum('actualSizeGain')/sum('elapsed'):null};}
function render(){if(!data||loading)return;const dimension=$('dimension').value,rows=data.runs.flatMap(r=>r.groups.map(g=>({...g,variant:r.variant}))).filter(r=>['type','band','personality','region'].every(k=>$(k).value==='all'||r[k]===$(k).value));const keys=[...new Set(rows.map(r=>r[dimension]))].sort((a,b)=>dimension==='time'?a-b:dimension==='band'?['20–39','40–79','80–159','160–399','400+'].indexOf(a)-['20–39','40–79','80–159','160–399','400+'].indexOf(b):String(a).localeCompare(String(b))),variants=[...new Set(data.runs.map(r=>r.variant))];const totals=aggregate(rows);$('status').textContent=`${data.runs.length}실행 · ${totals.samples}개체 표본 · ${data.policy??''} · 보상/심각도는 조건부 평균, 피해는 전체 노출 평균`;const colors=['#94a3b8','#38bdf8','#a78bfa','#fb923c','#a3e635','#34d399'];$('charts').replaceChildren();for(const [metric,title] of metrics){const box=document.createElement('article');box.className='chart';const heading=document.createElement('h3');heading.textContent=title;const c=document.createElement('canvas');c.width=900;c.height=360;const series=variants.map((v,i)=>({name:v,color:colors[i%colors.length],values:keys.map(k=>aggregate(rows.filter(r=>r.variant===v&&r[dimension]===k))[metric])}));if(metric==='meanSize'&&dimension==='time'&&$('type').value==='player'){const points=data.runs.find(r=>r.variant!=='baseline')?.config?.evaluation?.targetSizes??[];series.push({name:'기획 목표',color:'#fbbf24',values:keys.map(t=>targetSize(t+10,points))});}plot(c,series,keys,title);const note=document.createElement('p');note.className='legend';note.textContent='범례의 실행 이름으로 비교하세요. 노랑: 잠정 목표. 빈 구간은 표본 없음.';const save=document.createElement('button');save.textContent='PNG 저장';save.onclick=()=>{const a=document.createElement('a');a.href=c.toDataURL();a.download=`balance-${dimension}-${metric}.png`;a.click();};c.setAttribute('aria-label',title);const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='표본과 값';const table=document.createElement('table');const header=document.createElement('tr');for(const text of ['구간','실행','값','개체 표본']){const th=document.createElement('th');th.textContent=text;header.append(th);}table.append(header);keys.forEach((key,index)=>series.forEach(s=>{const tr=document.createElement('tr'),count=aggregate(rows.filter(r=>r.variant===s.name&&r[dimension]===key)).samples;for(const text of [key,s.name,Number.isFinite(s.values[index])?s.values[index].toFixed(2):'—',s.name==='기획 목표'?'목표':count]){const td=document.createElement('td');td.textContent=text;tr.append(td);}table.append(tr);}));details.append(summary,table);box.append(heading,c,note,save,details);$('charts').append(box);}
 renderSkills(data,colors);renderChannels(rows,keys,colors);renderWorld(data,colors);
 const drops=data.runs.flatMap(r=>(r.drops??[]).map(d=>({...d,variant:r.variant}))),absorptions=data.runs.flatMap(r=>(r.absorptions??[]).map(a=>({...a,variant:r.variant})));const rewardBins=['20–39','40–79','80–159','160–399','400+'],bandOf=s=>s<40?rewardBins[0]:s<80?rewardBins[1]:s<160?rewardBins[2]:s<400?rewardBins[3]:rewardBins[4];plot($('loot'),variants.map((v,i)=>({name:v,color:colors[i%colors.length],values:rewardBins.map(b=>{const a=drops.filter(d=>d.variant===v&&bandOf(d.size)===b);return a.length?a.reduce((s,d)=>s+d.droppedGrowth,0)/a.length:null;})})),rewardBins,'Dropped Growth');plot($('absorb'),[{name:'실제 드롭 수거 %',color:'#38bdf8',values:rewardBins.map(b=>{const a=drops.filter(d=>bandOf(d.size)===b),total=a.reduce((s,d)=>s+d.droppedGrowth,0);return total?a.reduce((s,d)=>s+d.collectedGrowth,0)/total*100:null;})}],rewardBins,'Collected %');$('loot-note').textContent=`사냥 ${drops.length}건 · 직접 흡수 ${absorptions.length}건. 직접 흡수의 대상/수신 Growth·면적 효율은 원본 JSON에 기록됩니다. 실험 종료 직전 드롭은 수거 대기 중일 수 있습니다.`;
 const lava=data.runs.flatMap(r=>(r.lava??[]).map(l=>({...l,variant:r.variant}))),bands=['20–39','40–79','80–159','160–399','400+'];const series=['red','other'].map((color,i)=>({name:color==='red'?'붉은 공':'다른 색',color:i?'#fbbf24':'#f87171',values:bands.map(b=>{const a=lava.filter(l=>(color==='red'?l.color==='red':l.color!=='red')&&(l.size<40?bands[0]:l.size<80?bands[1]:l.size<160?bands[2]:l.size<400?bands[3]:bands[4])===b&&l.variant!=='baseline');return a.length?a.reduce((s,l)=>s+l.hpRatio,0)/a.length*100:null;})}));plot($('lava'),series,bands,'HP%');$('lava-note').textContent=`용암 피해 로그 ${lava.length}건. 변경 후 실제 tick당 HP 손실 평균; 같은 크기의 표본 비교가 필요합니다. 관찰이 없는 400+ 구간은 빈 값입니다.`;}
function load(j){if(j.format==='ball-next-observation-v1'){if(!Array.isArray(j.samples))throw Error('관찰 samples 배열이 필요합니다.');const groups=j.samples.map((s,i)=>{const prev=j.samples[i-1];return{time:Math.floor(s.time/20)*20,type:'player',band:s.size<40?'20–39':s.size<80?'40–79':s.size<160?'80–159':s.size<400?'160–399':'400+',personality:s.personality??'survival-player',region:s.biome??s.region,samples:1,sampleSeconds:1,sizeSum:s.size,channelMeasured:!!s.opportunityChannels,anyOpportunities:+(s.opportunityChannels?.any??false),foodOpportunities:+(s.opportunityChannels?.food??false),absorptionOpportunities:+(s.opportunityChannels?.absorption??false),huntOpportunities:+(s.opportunityChannels?.hunt??false),realizedSamples:+!!s.realizedGrowth?.measured,realizedSuccesses:+!!s.realizedGrowth?.sufficient,realizedGainSum:s.realizedGrowth?.gain??0,realizedSeconds:s.realizedGrowth?.seconds??0,opportunityMeasured:typeof s.growthOpportunity==='boolean',crisisMeasured:typeof s.crisis==='boolean',opportunities:+(s.growthOpportunity??false),crises:+(s.crisis??false),rewardSum:s.growthOpportunity?s.potentialSizeGain:0,severitySum:s.crisis?s.crisisSeverity:0,hpMeasured:!!prev&&Number.isFinite(s.damageHpRatio)&&Number.isFinite(prev.damageHpRatio),hpLostRatio:prev&&Number.isFinite(s.damageHpRatio)&&Number.isFinite(prev.damageHpRatio)?Math.max(0,s.damageHpRatio-prev.damageHpRatio):0,opportunityStarts:+(s.growthOpportunity&&!prev?.growthOpportunity),crisisStarts:+(s.crisis&&!prev?.crisis),actualSizeGain:prev&&prev.defeats===s.defeats?s.size-prev.size:0,elapsed:prev&&prev.defeats===s.defeats?s.time-prev.time:0};});j={format:'ball-next-balance-v1',policy:'Imported player observation, 1-second samples; recent retained history only',runs:[{variant:'user',seed:j.seed,groups,config:j.config,lava:j.lavaLog??[],skills:j.skills}]};}if(j.format!=='ball-next-balance-v1')throw Error('밸런스 또는 관찰 JSON이 필요합니다.');if(!Array.isArray(j.runs)||j.runs.some(run=>!Array.isArray(run.groups)))throw Error('실행별 groups 배열이 필요합니다.');data=j;$('channel-variant').replaceChildren(new Option('전체','all'));for(const v of [...new Set(j.runs.map(r=>r.variant))])$('channel-variant').append(new Option(v,v));for(const k of ['band','personality','region']){$(k).replaceChildren(new Option('전체','all'));for(const v of [...new Set(j.runs.flatMap(r=>r.groups.map(g=>g[k])))].sort())$(k).append(new Option(v,v));}render();}
for(const k of ['type','band','personality','region','dimension'])$(k).onchange=render;
$('upload').onchange=async e=>{try{const incoming=JSON.parse(await e.target.files[0].text());loadVersion++;loading=false;load(incoming);userData=incoming;if(!$('dataset').querySelector('option[value="custom"]'))$('dataset').append(new Option('가져온 실행','custom'));$('dataset').value='custom';$('dataset-retry').hidden=true;}catch(error){$('status').textContent=error.message;}};
$('feedback-upload').onchange=async e=>{try{const j=JSON.parse(await e.target.files[0].text()),records=j.records??[],qualified=records.filter(r=>r.satisfaction>=4&&r.pressure>=2&&r.pressure<=4),buckets=new Map();for(const r of qualified){const key=Math.floor(r.time/60)*60;const a=buckets.get(key)??[];a.push(r.desiredSize);buckets.set(key,a);}const lines=[`전체 ${records.length}응답 · 긍정/적정 위기 ${qualified.length}응답`];for(const [time,a]of buckets)lines.push(`${time}~${time+59}초: ${a.length}응답 · 희망 크기 평균 ${(a.reduce((s,v)=>s+v,0)/a.length).toFixed(1)} · ${a.length<5?'표본 부족, 확정 보류':'개인 희망 평균 후보, 추가 사용자 검증 필요'}`);$('feedback').textContent=lines.join(' / ');}catch(error){$('feedback').textContent=error.message;}};
async function read(path){const r=await fetch(path);if(!r.ok)throw Error('데이터를 불러오지 못했습니다.');return r.json();}
const datasetCache=new Map();
async function datasetFor(name){
 if(name==='custom')return userData;
 if(datasetCache.has(name))return datasetCache.get(name);
 const pending=(async()=>{if(name==='colors')return read('./reports/M47-color-cohort.json');if(name==='policy')return read('./reports/M44-skill-policy.json');if(name==='food'){const [before,after]=await Promise.all(['M45-opportunity-balance','M46-density-balance'].map(file=>read(`./reports/${file}.json`)));return {...after,policy:'Same three seeds, normal Life: bounded food replenishment before/after; global ecology and routes may differ.',runs:[...before.runs.map(r=>({...r,variant:'M45-before'})),...after.runs]};}if(name==='skills')return read('./reports/M43-skill-balance.json');if(name==='growth')return read('./reports/M45-opportunity-balance.json');if(name==='comparison'){const [base,recovery,tuned,floor]=await Promise.all(['M41-balance','M41-recovery-balance','M41-tuned-balance','M41-floor-balance'].map(file=>read(`./reports/${file}.json`)));return {...base,runs:[...base.runs.filter(r=>r.variant==='baseline'),...recovery.runs,...tuned.runs,...floor.runs]};}const [long,tuned,baseline,floor]=await Promise.all(['M41-final-long-balance','M41-tuned-long-balance','M41-baseline-long-balance','M41-floor-long-balance'].map(file=>read(`./reports/${file}.json`)));return {...long,runs:[...baseline.runs,...long.runs,...tuned.runs,...floor.runs]};})();
 datasetCache.set(name,pending);try{return await pending;}catch(error){datasetCache.delete(name);throw error;}
}
async function selectDataset(){const version=++loadVersion;loading=true;$('status').textContent='선택한 실행을 읽는 중…';$('dataset-retry').hidden=true;try{const incoming=await datasetFor($('dataset').value);if(version!==loadVersion)return;loading=false;load(incoming);}catch(error){if(version!==loadVersion)return;loading=false;data=null;$('charts').replaceChildren();for(const c of document.querySelectorAll('canvas'))c.getContext('2d').clearRect(0,0,c.width,c.height);$('status').textContent=`${error.message} 다시 불러오거나 다른 실행을 선택하세요.`;$('dataset-retry').hidden=false;}}
$('dataset').onchange=selectDataset;$('dataset-retry').onclick=selectDataset;$('channel-variant').onchange=render;selectDataset();

function renderSkills(data,colors){
 const all=data.runs.flatMap(run=>(run.skills?.rows??[]).map(row=>({...row,variant:run.variant}))),rows=all.filter(row=>['type','band','personality','region'].every(key=>$(key).value==='all'||row[key]===$(key).value));
 $('skill-frequency').hidden=$('skill-damage').hidden=$('skill-hp').hidden=$('skill-support').hidden=!all.length;$('skill-table').parentElement.hidden=!all.length;
 const keys=[...new Set(rows.map(row=>`${row.color} ${row.slot}`))].sort(),variants=[...new Set(rows.map(row=>row.variant))];
 for(const [id,key,title]of [['skill-frequency','fires','완료 횟수 (선택된 실행의 누적)'],['skill-damage','damage','완료 시전당 직접 피해']])plot($(id),variants.map((variant,i)=>({name:variant,color:colors[i%colors.length],values:keys.map(label=>{const group=rows.filter(row=>row.variant===variant&&`${row.color} ${row.slot}`===label),sum=key=>group.reduce((s,row)=>s+row[key],0),fires=sum('fires');return id==='skill-frequency'?sum('fires'):fires?sum('damage')/fires:null;})})),keys,title);
 plot($('skill-hp'),variants.map((variant,i)=>({name:variant,color:colors[i%colors.length],values:keys.map(label=>{const group=rows.filter(row=>row.variant===variant&&`${row.color} ${row.slot}`===label),fires=group.reduce((a,r)=>a+r.fires,0);return fires?group.reduce((a,r)=>a+r.hpRatio,0)/fires*100:null;})})),keys,'완료 시전당 누적 직접 HP%');
 plot($('skill-support'),[['recruits','모집'],['summons','소환'],['buffs','강화 대상'],['marks','표식 대상']].map(([key,name],i)=>({name,color:colors[i+1],values:keys.map(label=>{const group=rows.filter(row=>`${row.color} ${row.slot}`===label),fires=group.reduce((a,r)=>a+r.fires,0);return fires?group.reduce((a,r)=>a+r[key],0)/fires:null;})})),keys,'완료 시전당 대상 수');
 const sum=key=>rows.reduce((s,row)=>s+row[key],0);
 const instant=rows.filter(r=>r.instantMeasured),aimSum=key=>instant.reduce((a,r)=>a+(r[key]??0),0);$('skill-aim-note').hidden=!instant.length;$('skill-aim-note').textContent=`순간 범위 진단: 시작 ${aimSum('instantStarts')} (처음 대상 없음 ${aimSum('emptyInstantStarts')}) · 완료 ${aimSum('instantFires')} (완료 때 대상 없음 ${aimSum('emptyInstantFires')}) · 초기 대상 범위 이탈 ${aimSum('escapedTargets')} · 사망/동행 등 상태 변화 ${aimSum('invalidatedTargets')} · 범위 안 무적 ${aimSum('invulnerableTargets')} · 시전자 원점 이동 평균 ${aimSum('instantFires')?(aimSum('originTravel')/aimSum('instantFires')).toFixed(1):'—'}. 순간 냉기/E 파동만 관찰하며 지속 장판/파도는 포함하지 않습니다. 이탈/무적은 대상 수, 없음은 시전 수입니다.`;
 const mixed=data.runs.some(run=>run.skills?.mixedConfiguration);
 $('skill-note').textContent=all.length?`${mixed?'실행 중 수치 변경으로 전후 합계가 섞였습니다. 같은 시드 재시작으로 비교하세요. ':''}시작 ${sum('starts')} · 완료 ${sum('fires')} · 취소 ${sum('cancelled')} · 모집 ${sum('recruits')} · 소환 ${sum('summons')}. 크기/성향/지역은 시전 당시 시전자 기준입니다. 피해는 직접 스킬 타격만이며 버프를 받은 일반 공격과 효과의 인과 가치는 제외합니다. 누적 HP%는 여러 대상·반복 tick의 합이라100%를 넘을 수 있고 타격 사건/시전 수는 명중률이 아닙니다. 강화에는 시전자 자신도 포함될 수 있습니다. 완료 횟수는 실행 시간과 개체 수에 따라 달라집니다.`:'이 파일에는 스킬 지표가 없습니다. M43 이상 관찰 또는 시뮬레이션 JSON을 가져오세요.';
 const container=$('skill-table');container.replaceChildren();const table=document.createElement('table'),head=document.createElement('tr');for(const label of ['실행','종족/슬롯','대상/크기/성향/지역','후보','시작','완료','취소','타격 사건','직접 피해','누적 HP%','모집','소환','강화','표적']){const cell=document.createElement('th');cell.textContent=label;head.append(cell);}table.append(head);
 for(const row of rows){const tr=document.createElement('tr');for(const value of [row.variant,`${row.color} ${row.slot}`,`${row.type} ${row.band} ${row.personality} ${row.region}`,row.skill,row.starts,row.fires,row.cancelled,row.hits,row.damage.toFixed(1),(row.hpRatio*100).toFixed(1),row.recruits,row.summons,row.buffs,row.marks]){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}container.append(table);
}

function renderChannels(rows,keys,colors){
 const chosen=$('channel-variant').value,measured=rows.filter(r=>r.channelMeasured&&(chosen==='all'||r.variant===chosen));$('channel-section').hidden=!measured.length;if(!measured.length)return;
 const dimension=$('dimension').value,sum=(list,key)=>list.reduce((a,r)=>a+(r[key]??0),0),rate=(key,k)=>{const group=measured.filter(r=>r[dimension]===k),count=sum(group,'samples');return count?sum(group,key)/count*100:null;};
 plot($('channel-kinds'),[['foodOpportunities','먹이'],['absorptionOpportunities','흡수'],['huntOpportunities','사냥'],['anyOpportunities','전체 잠재']].map(([key,name],i)=>({name,color:colors[i+1],values:keys.map(k=>rate(key,k))})),keys,'잠재 기회 노출 %');
 plot($('channel-realized'),[{name:'전체 잠재 기회 노출 %',color:'#34d399',values:keys.map(k=>rate('anyOpportunities',k))},{name:'최근 실제 성장 기준 충족 %',color:'#fbbf24',values:keys.map(k=>{const group=measured.filter(r=>r[dimension]===k),count=sum(group,'realizedSamples');return count?sum(group,'realizedSuccesses')/count*100:null;})}],keys,'노출 또는 실제 충족 %');
 const actualN=sum(measured,'realizedSamples');$('channel-note').textContent=`${sum(measured,'samples')}개체 표본 · 최근 실제 성장 ${actualN}개 측정 · 평균 관찰 기간 ${actualN?(sum(measured,'realizedSeconds')/actualN).toFixed(1):'—'}초. 먹이는 성장 유물 보너스를 반영합니다. 사냥은 성공·드롭 전량 회수, 흡수는 성공을 가정한 잠재 보상입니다. 추격·회피·회수 경쟁을 보장하지 않습니다. 위9개 그래프의 기존 먹이 지표와 구분하며, 사망/구간 부족은 실제 성장 미측정입니다.`;
}

function renderWorld(data,colors){
 const runs=data.runs.filter(run=>Array.isArray(run.timeline)&&run.timeline.some(t=>Number.isFinite(t.orbs)));$('world-section').hidden=!runs.length;if(!runs.length)return;
 const variants=[...new Set(runs.map(run=>run.variant))],times=[...new Set(runs.flatMap(run=>run.timeline.filter(t=>Number.isFinite(t.time)).map(t=>Math.round(t.time))))].sort((a,b)=>a-b),mean=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
 const series=variants.map((variant,i)=>({name:variant,color:colors[i%colors.length],values:times.map(time=>mean(runs.filter(run=>run.variant===variant).flatMap(run=>run.timeline.filter(t=>Math.round(t.time)===time&&Number.isFinite(t.orbs)).map(t=>t.orbs))))}));
 const targets=runs.map(run=>{const b=run.config;return b?.world&&b?.spawning?Math.min(b.spawning.maxOrbCount,Math.ceil((b.spawning.minimumOrbDensity??0)*b.world.worldWidth*b.world.worldHeight/1e6)):null;}).filter(Number.isFinite);if(targets.length&&targets.every(t=>t===targets[0]))series.push({name:'공통 밀도 목표',color:'#fbbf24',values:times.map(()=>targets[0])});
 plot($('world-orbs'),series,times,'전체 먹이 개수');$('world-note').textContent='세계 전체 먹이 수의 실행 평균입니다. 대상·크기·성향·지역 필터와 무관합니다. 일시 부족은 보충 상한 때문에 가능하며 평균이 개별 실행의 목표 달성을 보장하지 않습니다. 정책 변경은 모든 개체에 적용되어 이동 경로와 생태계가 함께 달라집니다.';
 const table=document.createElement('table'),head=document.createElement('tr');for(const title of ['실행','시드','진행 초','종료 이유','플레이어 패배','끝 Size','끝 먹이 수']){const cell=document.createElement('th');cell.textContent=title;head.append(cell);}table.append(head);for(const run of runs){const last=run.timeline.at(-1),row=document.createElement('tr');for(const value of [run.variant,run.seed,Number.isFinite(run.seconds)?run.seconds.toFixed(0):'—',run.stopped??'—',run.defeats??'—',Number.isFinite(last?.playerSize)?last.playerSize.toFixed(1):'—',last?.orbs??'—']){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}table.append(row);}$('world-runs').replaceChildren(table);
}
