import {realizedGrowthWindow} from './opportunityChannels.js';
import {growthFromSize,sizeFromGrowth} from './entity.js';
import {assessGameplay} from './gameplayEvaluation.js';
export function sizeBand(size){return size<40?'20–39':size<80?'40–79':size<160?'80–159':size<400?'160–399':size<500?'400–499':size<800?'500–799':size<1500?'800–1499':'1500+';}
export function targetSize(time,points=[]){if(!points.length)return null;const sorted=[...points].sort((a,b)=>a.seconds-b.seconds);if(time<=sorted[0].seconds)return sorted[0].size;for(let i=1;i<sorted.length;i++){const a=sorted[i-1],b=sorted[i];if(time<=b.seconds)return a.size+(b.size-a.size)*(time-a.seconds)/(b.seconds-a.seconds);}return sorted.at(-1).size;}
export class BalanceMetrics {
 constructor(game,variant){this.game=game;this.variant=variant;this.groups=new Map();this.previous=new Map();this.timeline=[];this.lava=[];this.drops=[];this.dropById=new Map();this.absorptions=[];this.realizedHistory=new Map();}
 row(e){const g=this.game,dimensions={time:Math.floor(g.gameTime/20)*20,type:e.behavior,band:sizeBand(e.size),personality:e.personality??'survival-player',region:g.biomes.regionAt(e)?.id??'none'},key=JSON.stringify(dimensions);if(!this.groups.has(key))this.groups.set(key,{...dimensions,samples:0,observedSeconds:0,sizeSum:0,channelMeasured:true,anyOpportunities:0,foodOpportunities:0,absorptionOpportunities:0,huntOpportunities:0,channelGainSum:0,realizedSamples:0,realizedSuccesses:0,realizedGainSum:0,realizedSeconds:0,opportunities:0,crises:0,rewardSum:0,severitySum:0,hpLostRatio:0,damage:0,hits:0,opportunityStarts:0,crisisStarts:0,actualSizeGain:0,elapsed:0});return this.groups.get(key);}
 drop(dead,orbs,direct){const entry={time:this.game.gameTime,size:dead.size,capitalGrowth:Math.max(0,dead.growth??0),bodyCapitalGrowth:growthFromSize(dead.baseSize??dead.size,this.game.balance.player.startingSize,this.game.balance.growth.growthToSizeRatio,this.game.balance.growth),directGrowth:direct,droppedGrowth:orbs.reduce((s,o)=>s+o.growthValue,0),collectedGrowth:0,collectorPlayerGrowth:0};this.drops.push(entry);for(const o of orbs)this.dropById.set(o.id,entry);}
 pickup(orb,eater,received=orb.growthValue){const entry=this.dropById.get(orb.id);if(!entry)return;entry.collectedGrowth+=received;if(eater.behavior==='player')entry.collectorPlayerGrowth+=received;this.dropById.delete(orb.id);}
 absorb(e,target,gain){this.absorptions.push({time:this.game.gameTime,absorberSize:e.size,targetSize:target.size,targetGrowth:target.growth??0,healthRecovered:target.absorptionHealthRecovered??0,healthCost:target.absorptionHealthPaid??0,healthCostRatio:(target.absorptionHealthPaid??0)/e.maxHp,receivedGrowth:gain,receivedSizeGain:sizeFromGrowth(e.growth+gain,e.baseSize,this.game.balance.growth.growthToSizeRatio,this.game.balance.growth)-e.size,transferredArea:Math.max(0,Math.pow(sizeFromGrowth(e.growth+gain,e.baseSize,this.game.balance.growth.growthToSizeRatio,this.game.balance.growth),2)-e.size*e.size),areaEfficiency:this.game.balance.absorption.areaEfficiency});}
 hit(e,damage,maxHp){const row=this.row(e);row.hpLostRatio+=damage/Math.max(1,maxHp);row.damage+=damage;row.hits++;}
 observe(){const g=this.game,units=g.entities.filter(e=>e.alive&&e.behavior!=='orb');for(const e of units){const a=assessGameplay(g,e),row=this.row(e),prev=this.previous.get(e.id),sameLife=prev&&prev.life===(e.defeatSerial??0);const history=this.realizedHistory.get(e.id)??[],current={time:g.gameTime,size:e.size,defeats:e.defeatSerial??0,growthNeeded:a.growthNeeded},actual=realizedGrowthWindow(history,current,Number(g.balance.evaluation.encounterSeconds));history.push(current);const retained=history.filter(s=>s.time>=g.gameTime-610).slice(-124);this.realizedHistory.set(e.id,retained);if(actual.measured){row.realizedSamples++;row.realizedSuccesses+=+actual.sufficient;row.realizedGainSum+=actual.gain;row.realizedSeconds+=actual.seconds;}row.anyOpportunities+=+a.opportunityChannels.any;row.foodOpportunities+=+a.opportunityChannels.food;row.absorptionOpportunities+=+a.opportunityChannels.absorption;row.huntOpportunities+=+a.opportunityChannels.hunt;row.channelGainSum+=a.opportunityChannels.potentialGain;if(prev)row.observedSeconds+=Math.max(0,g.gameTime-prev.time);row.samples++;row.sizeSum+=e.size;row.opportunities+=+a.growthOpportunity;row.crises+=+a.crisis;row.rewardSum+=a.growthOpportunity?a.potentialSizeGain:0;row.severitySum+=a.crisis?a.crisisSeverity:0;row.opportunityStarts+=+(a.growthOpportunity&&(!sameLife||!prev.opportunity));row.crisisStarts+=+(a.crisis&&(!sameLife||!prev.crisis));if(sameLife){row.actualSizeGain+=e.size-prev.size;row.elapsed+=g.gameTime-prev.time;}this.previous.set(e.id,{time:g.gameTime,size:e.size,life:e.defeatSerial??0,opportunity:a.growthOpportunity,crisis:a.crisis});}const live=new Set(units.map(e=>e.id));for(const id of this.previous.keys())if(!live.has(id)){this.previous.delete(id);this.realizedHistory.delete(id);}
 this.timeline.push({time:g.gameTime,meanSize:units.reduce((s,e)=>s+e.size,0)/units.length,playerSize:g.player.size,maxSize:Math.max(...units.map(e=>e.size)),population:units.length,orbs:g.entities.filter(e=>e.alive&&e.behavior==='orb').length,target:targetSize(g.gameTime,g.balance.evaluation.targetSizes)});}
 export(){return{variant:this.variant,seed:this.game.seed,seconds:this.game.gameTime,defeats:this.game.player.defeatSerial??0,stopped:this.game.gameOver?'game-over':'duration',config:this.game.balance,timeline:this.timeline,groups:[...this.groups.values()],lava:this.lava,drops:this.drops,absorptions:this.absorptions,skills:this.game.abilities.metrics.export()};}
}
