import {drawObjectArt} from './actionArt.js?forest-palette-04';
import {drawEnvironmentalArt} from './environmentArt.js?forest-palette-04';
import {BIOME_OBJECTS,objectPreset} from './biomeObjectCatalog.js?forest-palette-04';
import {dist} from './collision.js';import {spawnOrb} from './spawning.js';import {applyDamage} from './combat.js?forest-palette-04';import {delta,wrap,near} from './topology.js';import {terrainDamageMultiplier} from './biomes.js?forest-palette-04';
export function objectRole(c){return ['vent','vortex'].includes(c.effect)?'danger':c.effect==='current'?'movement':'benefit';}
export class BiomeObjects{
 constructor(game){this.game=game;this.objects=[];this.cooldowns=new Map();this.signature='';this.events=[];}
 sync(){const preset=objectPreset(this.game.balance),signature=JSON.stringify(preset);if(signature===this.signature)return;this.signature=signature;this.objects=[];
  for(const id of preset.enabled){const cfg={...BIOME_OBJECTS[id],...preset.overrides[id]},tiles=this.game.biomes.tiles.filter(t=>t.region.id===cfg.region);if(!tiles.length)continue;let hash=(this.game.seed>>>0);for(const char of id)hash=Math.imul(hash^char.charCodeAt(0),16777619)>>>0;
   for(let i=0;i<(['lake-current','lake-vortex'].includes(id)?Math.max(1,Math.ceil(preset.countPerType/6)):id==='desert-oasis'?Math.max(1,Math.ceil(preset.countPerType/3)):preset.countPerType);i++){const t=tiles[(hash+i*137)%tiles.length],o={id:`${id}:${i}`,candidate:id,config:cfg,x:t.x+100,y:t.y+100,_world:this.game.balance.world,phase:i*2};
    if(cfg.effect==='current'){const a=((hash+i)%4)*Math.PI/2,w=this.game.balance.world;o.points=[{x:o.x,y:o.y}];for(const sign of [-1,1]){const side=[];for(let k=1;k<=cfg.pathSteps;k++){const p={x:wrap(o.x+Math.cos(a)*k*200*sign,w.worldWidth),y:wrap(o.y+Math.sin(a)*k*200*sign,w.worldHeight)};if(this.game.biomes.regionAt(p)?.id!=='lake')break;side.push(p);}o.points=sign<0?[...side.reverse(),...o.points]:[...o.points,...side];}if(o.points.length<2)o.points=[{x:o.x,y:o.y},{x:o.x+Math.cos(a)*60,y:o.y+Math.sin(a)*60}];o.width=Math.min(cfg.widthMax,Math.max(cfg.widthMin,cfg.widthMin+(hash+i*37)%(Math.max(1,cfg.widthMax-cfg.widthMin+1))));o.reach=cfg.pathSteps*200+o.width;}
    const scale=.8+((hash+i*73)%401)/1000;o.visualScale=scale;o.config={...cfg,radius:cfg.radius*scale*(id==='lake-vortex'?1.4:1),...(id==='desert-oasis'?{power:cfg.power*2}:{})};if(id==='lake-current'){o.width*=1.4;o.reach=cfg.pathSteps*200+o.width;}this.objects.push(o);
   }
  }
 }
 // R-WORLD-004: shelter cures immediately for everyone inside, not only cooldown winner.
 inFrostShelter(e){if(!this.game.biomes.enabled)return false;return this.objects.some(o=>o.config.effect==='frost'&&dist(o,e)<=o.config.radius+e.size/2);}
 activeVent(o){return (this.game.gameTime+o.phase)%o.config.cycleDuration<Math.min(o.config.activeDuration,o.config.cycleDuration);}
 currentVector(o,e){let best=null;for(let i=1;i<o.points.length;i++){const a={...o.points[i-1],_world:o._world},v=delta(a,o.points[i]),p=delta(a,e),len=Math.hypot(v.x,v.y);if(!len)continue;const t=Math.max(0,Math.min(1,(p.x*v.x+p.y*v.y)/(len*len))),d=Math.hypot(p.x-v.x*t,p.y-v.y*t);if(d<=o.width/2+e.size/2&&(!best||d<best.d))best={x:v.x/len,y:v.y/len,d};}return best;}
 spawnRewards(o){const g=this.game,c=o.config;let capacity=Math.max(0,g.balance.spawning.maxOrbCount-g.entities.filter(e=>e.alive&&e.behavior==='orb').length);const total=c.count+(c.effect==='berry-spawner'?1:0);for(let i=0;i<total&&capacity>0;i++,capacity--){const orb=spawnOrb(g.balance,{x:o.x+Math.cos(i*2*Math.PI/total)*35,y:o.y+Math.sin(i*2*Math.PI/total)*35});orb.growthValue=c.growth*(g.biomes.blizzard()?(c.blizzardMultiplier??1):1);orb.regionReward=c.region;if(c.effect==='berry-spawner'&&i===0){orb.growthValue=0;orb.healFraction=c.healFraction;orb.colorHex='#f472b6';}g.entities.push(orb);}}
 update(dt=1/60){if(!this.game.biomes.enabled)return;this.sync();const g=this.game,now=g.gameTime,maxRadius=g.entities.reduce((m,e)=>e.alive?Math.max(m,e.size/2):m,0);
  for(const o of this.objects){const c=o.config,ready=(this.cooldowns.get(o.id)??0)<=now;
   if(c.effect==='berry-spawner'){if(ready){this.spawnRewards(o);this.cooldowns.set(o.id,now+c.cooldown);}continue;}
   const environmental=['vent','current','vortex'].includes(c.effect);const continuous=['desert-oasis','snow-shelter'].includes(o.candidate);if(!environmental&&!continuous&&!ready)continue;
   const actors=g.getNearbyEntities(o,(o.reach??c.radius)+maxRadius).filter(e=>e.alive&&(['player','ai'].includes(e.behavior)||['current','vortex'].includes(c.effect)&&e.behavior==='orb')).filter(e=>c.effect==='current'?this.currentVector(o,e):dist(o,e)<=c.radius+e.size/2).sort((a,b)=>dist(o,a)-dist(o,b)||a.id-b.id);
   if(environmental){for(const e of actors){if(c.effect==='vent'){if(ready&&this.activeVent(o))applyDamage(e,e.maxHp*c.hpFraction*c.tickInterval,g,null,g.balance,{kind:'field',ignoreDefense:true,postDefenseMultiplier:terrainDamageMultiplier(e.size,g.balance),knockback:false});continue;}
     if(c.effect==='vortex'&&dist(o,e)>c.radius)continue;const v=c.effect==='current'?this.currentVector(o,e):delta(e,o),len=Math.hypot(v.x,v.y);if(!len)continue;const resistance=e.behavior==='orb'?c.speed:Math.min(c.speed,e.moveSpeed*(g.biomes.moveMultiplier(e)??1)*.25);const move=c.effect==='current'?resistance*dt:Math.min(len,c.speed*dt*Math.max(.15,1-len/c.radius));e.x=wrap(e.x+v.x/len*move,g.balance.world.worldWidth);e.y=wrap(e.y+v.y/len*move,g.balance.world.worldHeight);
    }if(c.effect==='vent'&&ready&&this.activeVent(o))this.cooldowns.set(o.id,now+c.tickInterval);continue;}
   // User: these landmarks benefit every actor remaining inside; no shared consumption.
   if(continuous){for(const e of actors){if(c.effect==='heal')e.hp=Math.min(e.maxHp,e.hp+e.maxHp*c.power/Math.max(.001,c.cooldown)*dt);}continue;}
   const e=actors.find(e=>c.effect!=='heal'||e.hp<e.maxHp);if(!e)continue;this.cooldowns.set(o.id,now+c.cooldown);
   if(c.effect==='food')this.spawnRewards(o);
   if(c.effect==='heal')e.hp=Math.min(e.maxHp,e.hp+e.maxHp*c.power);
   if(c.effect==='shield'){e.shieldHp=Math.max(e.shieldHp??0,e.maxHp*c.power);e.shieldRemaining=Math.max(e.shieldRemaining??0,c.duration);}
   if(c.effect==='speed'){e.objectSpeedUntil=now+c.duration;e.objectSpeedMultiplier=1+c.power;if(c.hpCost)applyDamage(e,e.maxHp*c.hpCost,g,null,g.balance,{kind:'field',ignoreDefense:true,knockback:false});}
   if(c.effect==='charm'){e.companionCharmUntil=now+c.duration;e.companionCharmPower=c.power;e.companionDecoration=o.candidate==='lake-garland'?'shell':'flower';}
   if(c.effect==='wind-stack'){e.windStoneStacks=(e.windStoneStacks??0)+1;if(e.windStoneStacks>=c.stacksRequired){e.windStoneStacks=0;e.objectSpeedUntil=now+c.duration;e.objectSpeedMultiplier=1+c.power;}g.spawnFloatingText(e.x,e.y,`바람 ${e.windStoneStacks}/${c.stacksRequired}`,'#7dd3fc');}
   if(c.effect==='obsidian'){e.obsidianStacks=(e.obsidianStacks??0)+1;if(e.obsidianStacks>=c.stacksRequired){e.obsidianStacks=0;e.obsidianShieldHp=e.obsidianShieldMax=e.maxHp*c.shieldFraction;e.obsidianShieldUntil=now+c.duration;e.obsidianPower=c.power;}g.spawnFloatingText(e.x,e.y,`흑요석 ${e.obsidianStacks}/${c.stacksRequired}`,'#c4b5fd');}
   if(c.effect==='frost'){e.objectFrostUntil=now+c.duration;e.objectFrostResistance=c.power;}
   g.spawnFloatingText(o.x,o.y,c.name,'#bae6fd');this.events.push({time:now,id:o.id,actor:e.id,effect:c.effect});if(this.events.length>200)this.events.shift();
  }
 }
 draw(ctx,zoom){if(!this.game.biomes.enabled)return;this.sync();const camera=this.game.renderCamera??this.game.camera;for(const o of this.objects){const c=o.config,extent=o.reach??c.radius;if(Math.abs(o.x-camera.x)>this.game.canvas.width/2/zoom+extent||Math.abs(o.y-camera.y)>this.game.canvas.height/2/zoom+extent)continue;const role=objectRole(c),active=c.effect==='vent'?this.activeVent(o):true,ready=(this.cooldowns.get(o.id)??0)<=this.game.gameTime;ctx.save();ctx.globalAlpha=['current','vortex','vent'].includes(c.effect)?.8:['forest-tree','snow-flowers','snow-shelter','desert-oasis'].includes(o.candidate)?.85:ready?.85:.35;ctx.strokeStyle=role==='danger'?(c.effect==='vortex'?'#89bbc9aa':active?'#dba06eaa':'#817c7b77'):role==='movement'?'#86bbc7':'#a1bba0';ctx.fillStyle=role==='danger'?(c.effect==='vortex'?'#184c6810':active?'#934e2710':'#45424a08'):'#294c3420';ctx.lineWidth=1.2/zoom;
   if(c.effect==='current'){for(let i=1;i<o.points.length;i++){const a=near(o,o.points[i-1]),b=near(a,o.points[i]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineWidth=o.width;ctx.lineCap='round';ctx.strokeStyle='#28617d24';ctx.stroke();drawEnvironmentalArt(ctx,o,{a,b});const angle=Math.atan2(b.y-a.y,b.x-a.x),x=(a.x+b.x)/2,y=(a.y+b.y)/2;ctx.lineWidth=1.5/zoom;ctx.strokeStyle='#92c6cb88';ctx.beginPath();ctx.moveTo(x-9*Math.cos(angle)/zoom,y-9*Math.sin(angle)/zoom);ctx.lineTo(x+9*Math.cos(angle)/zoom,y+9*Math.sin(angle)/zoom);ctx.lineTo(x+4*Math.cos(angle+Math.PI/2)/zoom,y+4*Math.sin(angle+Math.PI/2)/zoom);ctx.stroke();}ctx.restore();continue;}
   const environmentalImage=drawEnvironmentalArt(ctx,o,{active});ctx.beginPath();ctx.arc(o.x,o.y,c.radius,0,Math.PI*2);ctx.fill();ctx.setLineDash(role==='danger'?[5/zoom,7/zoom]:[]);ctx.stroke();ctx.setLineDash([]);if(c.effect==='vortex'&&!environmentalImage){ctx.save();ctx.beginPath();for(let i=0;i<=60;i++){const angle=i*Math.PI/10,rr=c.radius*.75*i/60,x=o.x+Math.cos(angle)*rr,y=o.y+Math.sin(angle)*rr;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.strokeStyle='#fb923c';ctx.lineWidth=3/zoom;ctx.stroke();ctx.restore();}
   ctx.beginPath();if(role==='danger'){/* Environmental danger is conveyed by its real boundary and heat/water body. */}ctx.stroke();if(role==='benefit')drawObjectArt(ctx,o,zoom,ready);ctx.font=`${11/zoom}px system-ui`;ctx.textAlign='center';ctx.fillStyle='#e2e8f0';ctx.fillText(`${role==='danger'?'⚠ ':role==='benefit'?'+ ':''}${c.name}${c.effect==='vent'?(active?' · 분출 중':' · 휴식'):''}`,o.x,o.y-c.radius-7/zoom);ctx.restore();}}
}


