const KEY='ball-next-designer-answers-v1';
// R-META-007: data becomes plain text, never executable HTML; answers are local until exported.
export function validateQuestion(q){if(!q||typeof q.id!=='string'||!q.id||q.id.length>100||typeof q.title!=='string'||!q.title.trim()||q.title.length>500||q.options&&!Array.isArray(q.options))throw Error('의견 질문 형식이 잘못됐습니다.');const options=(q.options??[]).map(x=>String(x).slice(0,200));if(options.length>6)throw Error('선택지는 6개 이하로 작성하세요.');return {id:q.id,revision:String(q.revision??1),title:q.title,detail:String(q.detail??'').slice(0,5000),options,context:q.context??null};}
export class DesignerReview{
 constructor(getGame){this.getGame=getGame;this.queue=[];this.active=null;try{this.answers=JSON.parse(localStorage.getItem(KEY)??'[]');if(!Array.isArray(this.answers))this.answers=[];}catch{this.answers=[];}this.dialog=document.createElement('dialog');this.dialog.id='designer-review';this.dialog.setAttribute('aria-label','기획자 의견 요청');this.dialog.style.cssText='max-width:min(560px,90vw);max-height:85dvh;overflow:auto;background:#111827;color:#e2e8f0;border:1px solid #64748b;border-radius:14px;padding:22px';document.body.append(this.dialog);document.addEventListener('close',()=>setTimeout(()=>this.next(),0),true);this.dialog.addEventListener('cancel',e=>{e.preventDefault();this.finish(null);});this.dialog.addEventListener('keydown',e=>e.stopPropagation());this.dialog.addEventListener('keyup',e=>e.stopPropagation());}
 ask(raw){const q=validateQuestion(raw);return new Promise(resolve=>{this.queue.push({q,resolve});this.next();});}
 next(){if(this.active||!this.queue.length||document.querySelector('dialog[open]'))return;this.active=this.queue.shift();const {q}=this.active,g=this.getGame();this.previousPaused=g?.paused??false;if(g){g.paused=true;g.stopContinuousAudio();g.input.keys.clear();g.input.mouseDown=false;g.input._attackQueued=null;g.input.absorbHeld=false;g.input.sprintHeld=false;g.input.touchMove={x:0,y:0};g.input._dodgeQueued=false;g.input.dodge=false;g.input._specialQueued=false;g.input._ultimateQueued=false;g.input.spaceHeldSeconds=0;g.touchAim=null;}this.dialog.replaceChildren();const title=document.createElement('h2');title.textContent=q.title;const detail=document.createElement('p');detail.textContent=q.detail;const form=document.createElement('form');form.method='dialog';this.notes=document.createElement('textarea');this.notes.placeholder='이유·느낌·추가 의견';this.notes.rows=4;this.notes.style.cssText='box-sizing:border-box;width:100%;margin:14px 0';const select=document.createElement('select');select.setAttribute('aria-label','의견 선택');for(const value of ['선택해주세요',...q.options]){const option=document.createElement('option');option.textContent=value;option.value=value==='선택해주세요'?'':value;select.append(option);}this.choice=select;const save=document.createElement('button');save.type='submit';save.textContent='의견 저장';const later=document.createElement('button');later.type='button';later.textContent='나중에';later.onclick=()=>this.finish(null);form.append(select,this.notes,save,later);form.onsubmit=e=>{e.preventDefault();if(!select.value&&!this.notes.value.trim())return;this.finish({choice:select.value,note:this.notes.value.trim()});};this.dialog.append(title,detail,form);this.dialog.showModal();}
 finish(value){if(!this.active)return;const {q,resolve}=this.active;if(value){const {context:questionContext,...question}=q;const row={question,answer:value,time:new Date().toISOString(),context:q.context??this.getGame()?.snapshot?.()??null};this.answers.push(row);this.answers=this.answers.slice(-200);try{localStorage.setItem(KEY,JSON.stringify(this.answers));}catch{/* Export remains available if this browser denies local storage. */}}this.dialog.close();const g=this.getGame();if(g){g.input.keys.clear();g.input.mouseDown=false;g.input._attackQueued=null;g.input._specialQueued=false;g.input._ultimateQueued=false;g.paused=this.previousPaused;}this.active=null;resolve(value);setTimeout(()=>this.next(),0);}
 async poll(){if(this.polling)return;this.polling=true;try{const remote=location.hostname.endsWith('githack.com'),url=remote?'https://raw.githubusercontent.com/qwerzaq56-sketch/ball-game-next/codex/cloud-next-m4/data/designer-questions.json':'data/designer-questions.json';const response=await fetch(url+`?t=${Date.now()}`,{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!response.ok)return;const data=await response.json();if(data.format!=='ball-next-questions-v1'||!Array.isArray(data.questions))return;for(const raw of data.questions.slice(0,20)){let q;try{q=validateQuestion(raw);}catch{continue;}if(this.answers.some(a=>a.question?.id===q.id&&a.question?.revision===q.revision)||this.active?.q.id===q.id||this.queue.some(a=>a.q.id===q.id)||this.deferred?.has(q.id+q.revision))continue;this.ask(q).then(answer=>{if(!answer){this.deferred??=new Set();this.deferred.add(q.id+q.revision);}});}this.next();}catch{/* Offline gameplay remains available. */}finally{this.polling=false;}}
 start(){this.poll();this.timer=setInterval(()=>{this.poll();this.next();},30000);}
 export(){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({format:'ball-next-designer-answers-v1',answers:this.answers},null,2)],{type:'application/json'}));a.href=url;a.download='designer-answers.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
}
