import {Game} from './game.js';import {AIEntity,updateAI} from './ai.js';import {growthFromSize} from './entity.js';import {updateAttack,updateDodge} from './combat.js?art-release-01';import {spawnOrb} from './spawning.js';
export const ROOM_DEFAULT={seed:7,roomSize:1800,playerSize:100,targetSize:90,targetHp:1,playerColor:'blue',targetColor:'red',distance:260,count:1,targetApex:false,behavior:'dummy',apex:false};
// R-META-006: experiments clone production balance and never touch normal-run saves.
export function roomSettings(raw={}){const c={...ROOM_DEFAULT,...raw};for(const [key,min,max]of [['seed',0,4294967295],['roomSize',800,6000],['playerSize',20,1500],['targetSize',20,1500],['targetHp',.01,1],['distance',0,3000],['count',0,12]])if(!Number.isFinite(c[key])||c[key]<min||c[key]>max)throw Error(`잘못된 실험 조건: ${key}`);for(const k of ['seed','count'])if(!Number.isInteger(c[k]))throw Error(`${k}는 정수여야 합니다.`);if(!['blue','cyan','green','red','yellow'].includes(c.playerColor)||!['blue','cyan','green','red','yellow'].includes(c.targetColor)||!['dummy','ai'].includes(c.behavior))throw Error('색 또는 행동 설정이 잘못됐습니다.');if(typeof c.apex!=='boolean'||typeof c.targetApex!=='boolean')throw Error('최상위 상태는 참/거짓이어야 합니다.');if(c.roomSize<Math.max(c.playerSize,c.targetSize)+200||c.distance>c.roomSize-Math.max(c.playerSize,c.targetSize)-100)throw Error('방을 키우거나 크기·중심 거리를 줄이세요.');return c;}
export function roomBalance(source,settings){const b=structuredClone(source);b.world={...b.world,worldWidth:settings.roomSize,worldHeight:settings.roomSize,wrap:false};b.biomes.enabled=false;b.era.enabled=false;b.relics.enabled=false;b.spawning.initialOrbCount=0;b.spawning.initialEnemyCount=0;return b;}
export class SimulationRoom extends Game{
 initWorld(){} // R-META-006: no ambient food, enemies, relics, eras or terrain hazards.
 reset(){super.reset();const c=roomSettings(this.options.scenario);this.scenario=c;this.samples=[];this.sampleClock=0;this.initialHp=new Map();this.ecology.update=()=>{};const p=this.player;p.color=c.playerColor;p.colorHex=this.balance.colors.find(x=>x.id===p.color).color;p.growth=growthFromSize(c.playerSize,p.baseSize,this.balance.growth.growthToSizeRatio,this.balance.growth);p.refreshFromGrowth(this.balance);p.hp=p.maxHp;p._recomputeStacks(this.balance,false);p.apex=c.apex;p._specialApex=c.apex;p.specialCooldown=0;p.displayName='실험자';p.x=c.roomSize/2-c.distance/2;p.y=c.roomSize/2;this.entities=[p];for(let i=0;i<c.count;i++){const t=new AIEntity({balance:this.balance,x:p.x+c.distance,y:p.y+(i-(c.count-1)/2)*Math.min(160,c.roomSize/(c.count+1)),startSize:20,color:c.targetColor,colorHex:this.balance.colors.find(x=>x.id===c.targetColor).color});t.addGrowth(growthFromSize(c.targetSize,t.baseSize,this.balance.growth.growthToSizeRatio,this.balance.growth),this.balance);t.hp=t.maxHp*c.targetHp;t.roomBehavior=c.behavior;t.apex=t._specialApex=c.targetApex;t.specialCooldown=0;t.displayName=`대상 ${i+1}`;this.entities.push(t);}this.clampAllToWorld();for(const e of this.entities)this.initialHp.set(e.id,e.hp);this.camera={x:c.roomSize/2,y:c.roomSize/2,zoom:1};this.buildGrid();this.paused=true;this.audio.enabled=false;}
 updateAIEntity(e,dt,b){if(e.roomBehavior==='ai'||e.summoned)updateAI(e,dt,this,b);else{updateAttack(e,dt,b,this.hostileTargetsFor(e),this);updateDodge(e,dt,b);}}
 orbSpawnLoop(){} enemySpawnLoop(){} onEntityDeath(e){e.alive=false;this.abilities.release(e);this.allyLinks.leave(e,'room-death');if(e===this.player)this.gameOver=true;}
 handlePlayerDefeat(){this.player.alive=false;this.gameOver=true;this.paused=true;}
 updateCamera(){const z=Math.min(this.canvas.width,this.canvas.height)/this.scenario.roomSize*.9;this.camera={x:this.scenario.roomSize/2,y:this.scenario.roomSize/2,zoom:z*(this.viewZoom??1)};}
 update(dt){if(this.paused)return;super.update(dt);this.sampleClock+=dt;if(this.sampleClock>=.1){this.sampleClock%=.1;const targets=this.entities.filter(e=>e!==this.player&&e.behavior==='ai');this.samples.push({time:this.gameTime,playerHp:this.player.hp,playerMaxHp:this.player.maxHp,size:this.player.size,targetHp:targets.reduce((s,e)=>s+Math.max(0,e.hp),0),damage:targets.reduce((s,e)=>s+(e.damageReceived??0),0),defeated:targets.filter(e=>!e.alive).length,targetMaxHp:targets.reduce((s,e)=>s+e.maxHp,0),progress:Math.max(0,...targets.map(e=>e.absorptionRequired>0?e.absorptionProgress/e.absorptionRequired:0)),shield:this.player.shieldHp??0});if(this.samples.length>6000)this.samples.shift();}}
 cleanupDead(){} // Keep measured victims for results rather than spawning rewards.
 food(count=5){for(let i=0;i<count;i++){const e=spawnOrb(this.balance,{x:this.player.x+60+i*25,y:this.player.y});this.entities.push(e);}this.buildGrid();}
 export(){return {format:'ball-next-room-v1',scenario:structuredClone(this.scenario),balance:structuredClone(this.balance),elapsed:this.gameTime,samples:structuredClone(this.samples),units:this.entities.map(e=>({id:e.id,name:e.displayName,size:e.size,hp:e.hp,maxHp:e.maxHp,alive:e.alive,paid:e.absorptionHealthPaid??0,recovered:e.absorptionHealthRecovered??0}))};}
}
