import {SimulationRoom,ROOM_DEFAULT,roomSettings,roomBalance} from './simulationRoom.js';import {SkillTuningUI} from './skillTuningUI.js';import {DesignerReview} from './designerReview.js';
const $=id=>document.getElementById(id),canvas=$('room'),ctx=canvas.getContext('2d'),source=await (await fetch('config/gameBalance.json')).json(),working=structuredClone(source);let game,baseline=structuredClone(working),comparison=null,actionStarted=false,accumulator=0;
const fields={seed:['시드',0,4294967295],roomSize:['방 한 변',800,6000],playerSize:['내 Size',20,1500],targetSize:['대상 Size',20,1500],targetHp:['대상 HP 비율',.01,1],distance:['중심 거리',0,3000],count:['측정 대상 수',0,12],playerColor:['내 종족',['blue','cyan','green','red','yellow']],targetColor:['대상 종족',['blue','cyan','green','red','yellow']],behavior:['대상 행동',['dummy','ai']],apex:['내 최상위 상태',true],targetApex:['대상 최상위 상태',true]};
for(const [key,[title,min,max]]of Object.entries(fields)){const row=document.createElement('label');row.textContent=title;const input=Array.isArray(min)?document.createElement('select'):document.createElement('input');input.id='condition-'+key;if(Array.isArray(min)){for(const value of min){const o=document.createElement('option');o.value=value;o.textContent=value==='dummy'?'고정 표적':value==='ai'?'실제 AI':value;input.append(o);}input.value=ROOM_DEFAULT[key];}else if(min===true){input.type='checkbox';input.checked=ROOM_DEFAULT[key];}else{input.type='number';input.min=min;input.max=max;input.step=key==='targetHp'?'.05':'1';input.value=ROOM_DEFAULT[key];}row.append(input);$('settings').append(row);}
const parameters=[['combatScaling.baseAttackDamage','기본 공격 피해',1,500],['attack.manualChargeSeconds','풀 충전 시간',.1,5],['absorption.pullForce','기본 흡인력',0,5],['absorption.bluePullMultiplier','파랑 흡인 배율',.1,5],['absorption.maxAbsorptionSpeed','흡수 진행 속도',.1,20],['absorption.resistancePerSize','크기당 흡수 저항시간',.001,.1],['absorption.woundedCostFloor','부상 흡수 비용 하한',0,1],['growth.paceMultiplier','성장 수신 배율',.1,2],['sprint.speedMultiplier','달리기 이동 배율',1,4]];
const read=(b,path)=>path.split('.').reduce((v,k)=>v[k],b);function write(b,path,value){const parts=path.split('.'),key=parts.pop();parts.reduce((v,k)=>v[k],b)[key]=value;}
for(const [path,title]of parameters){const o=document.createElement('option');o.value=path;o.textContent=title;$('parameter').append(o);}
function syncParameter(){const [path,,min,max]=parameters.find(x=>x[0]===$('parameter').value);$('value').value=read(working,path);$('value').min=min;$('value').max=max;}
$('parameter').onchange=syncParameter;$('value').onchange=()=>{const [path,,min,max]=parameters.find(x=>x[0]===$('parameter').value),n=Number($('value').value);if(!Number.isFinite(n)||n<min||n>max){status('표시된 최소·최대 범위 안의 숫자를 입력하세요.');return;}write(working,path,n);status('B 수치를 변경했습니다. 방 재설정 또는 A/B 비교에 적용됩니다.');};syncParameter();new SkillTuningUI(working,$('skills'),{persist:false});
function status(text){$('status').textContent=text;}
function conditions(){const raw={};for(const [key,[,min]]of Object.entries(fields)){const node=$('condition-'+key);raw[key]=min===true?node.checked:Array.isArray(min)?node.value:Number(node.value);}return roomSettings(raw);}
function input(){const i={keys:new Set(),mouseX:canvas.width/2,mouseY:canvas.height/2,mouseDown:false,absorbToggle:false,dodge:false,consumeSpecial(){const v=this._specialQueued;this._specialQueued=false;return v;},consumeDodge(){const v=this.dodge;this.dodge=false;return v;}};return i;}
function create(balance,c){return new SimulationRoom(roomBalance(balance,c),canvas,input(),{showUnlock(){},showDefeatMessage(){}},{seed:c.seed,simulationRoom:true,scenario:c});}
function execute(g){const operation=$('operation').value,charge=Number($('charge').value);if(!Number.isFinite(charge)||charge<0||charge>1)throw Error('충전은 0~1입니다.');if(operation==='attack'){if(!g.player.attackUnlocked)throw Error('공격 해금 크기 이상으로 설정하세요.');g.input._attackQueued={charge,angle:0};}if(['E','R'].includes(operation)&&!g.abilities.start(g.player,0,null,null,operation))throw Error(`${operation} 해금·최상위 조건을 확인하세요.`);if(operation==='absorb'){if(g.scenario.targetColor!==g.scenario.playerColor||g.scenario.targetSize>=g.scenario.playerSize)throw Error('흡수 실험은 같은 색의 더 작은 대상을 설정하세요.');g.input.absorbToggle=true;}}
function reset(){game?.stopContinuousAudio();game=create(working,conditions());window.__room=game;actionStarted=false;comparison=null;$('comparison').textContent='';game.updateCamera();status('방을 재설정했습니다. 지정 대상 외 자동 소환은 없습니다.');}
function safe(fn){return()=>{try{fn();}catch(e){status(e.message);}};}
$('reset').onclick=safe(reset);$('play').onclick=safe(()=>{if(game.gameOver)throw Error('방을 재설정하세요.');if(!actionStarted){execute(game);actionStarted=true;}game.paused=!game.paused;});$('step').onclick=safe(()=>{if(!actionStarted){execute(game);actionStarted=true;}game.paused=false;game.update(1/60);game.paused=true;});$('food').onclick=()=>game.food();$('baseline').onclick=()=>{baseline=structuredClone(working);status('현재 수치 전체를 A로 고정했습니다. B는 이후 수정한 수치입니다.');};
$('compare').onclick=safe(()=>{if($('operation').value==='manual')throw Error('A/B 자동 비교는 고정 행동을 선택하세요.');const c=conditions(),operation=$('operation').value,charge=Number($('charge').value),duration=Number($('duration').value),runs={};if(!Number.isInteger(duration)||duration<1||duration>60)throw Error('비교 시간은 1~60초의 정수입니다.');game?.stopContinuousAudio();for(const [name,b]of [['A',baseline],['B',working]]){const run=create(b,c);execute(run);run.paused=false;for(let i=0;i<duration*60&&!run.gameOver;i++)run.update(1/60);run.paused=true;runs[name]=run.export();if(name==='B')game=run;}actionStarted=true;window.__room=game;comparison={format:'ball-next-room-comparison-v1',scenario:c,operation,charge,duration,runs};window.__roomComparison=comparison;const last=r=>r.samples.at(-1),a=last(runs.A),b=last(runs.B);$('comparison').textContent=`동일 시드·대상·행동 ${duration}초 / 조건은 JSON에 저장\nA 누적 피해 ${Math.round(a?.damage??0)} · Size ${a?.size.toFixed(1)} · 잔존 대상 ${runs.A.units.filter(e=>e.name?.startsWith('대상')&&e.alive).length} · 흡수 진행 ${Math.round((a?.progress??0)*100)}%\nB 누적 피해 ${Math.round(b?.damage??0)} · Size ${b?.size.toFixed(1)} · 잔존 대상 ${runs.B.units.filter(e=>e.name?.startsWith('대상')&&e.alive).length} · 흡수 진행 ${Math.round((b?.progress??0)*100)}%\n피해 차이 ${Math.round((b?.damage??0)-(a?.damage??0))}`;status('A/B 완료. 수치 차이를 확인한 후 의견을 남길 수 있습니다.');});
function download(data,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').onclick=()=>download(comparison??{...game.export(),operation:$('operation').value,charge:Number($('charge').value)},'simulation-room.json');
const review=new DesignerReview(()=>game);window.__designerReview=review;review.start();$('answers').onclick=()=>review.export();$('review').onclick=()=>review.ask({id:'room-feel-'+Date.now(),title:'이 조건에서 전투·흡수 속도는 어떻게 느껴지나요?',detail:'직접 관찰한 결과와 A/B 차이를 평가해주세요. 답변은 이 브라우저에 저장되며 JSON으로 내보낼 수 있습니다.',options:['A가 적절함','B가 적절함','둘 다 너무 강함/빠름','둘 다 너무 약함/느림','다른 조정이 필요함'],context:comparison??game.export()});
window.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,dialog'))return;const k=e.key.toLowerCase();if(k===' '){e.preventDefault();game.input.keys.add(' ');}else game.input.keys.add(k);if(k==='e')game.input._specialQueued=true;if(k==='r')game.input._ultimateQueued=true;});window.addEventListener('keyup',e=>{if(e.target.closest('input,select,textarea,dialog'))return;const k=e.key.toLowerCase();if(k===' '&&(game.input.spaceHeldSeconds??0)<.18)game.input.dodge=true;game.input.keys.delete(k);});window.addEventListener('blur',()=>{game.input.keys.clear();game.input.mouseDown=false;game.input.absorbHeld=false;game.paused=true;});
function point(e){const rect=canvas.getBoundingClientRect();game.input.mouseX=(e.clientX-rect.left)*canvas.width/rect.width;game.input.mouseY=(e.clientY-rect.top)*canvas.height/rect.height;}
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{if(game.paused)return;point(e);canvas.setPointerCapture(e.pointerId);if(e.button===2)game.input.absorbHeld=true;else{game.input.mouseDown=true;game.input.attackChargeSeconds=0;}};canvas.onpointermove=point;canvas.onpointerup=e=>{point(e);if(e.button===2)game.input.absorbHeld=false;else if(game.input.mouseDown&&!game.paused){const pos=game.screenToWorld(game.input.mouseX,game.input.mouseY);game.input._attackQueued={charge:Math.min(1,(game.input.attackChargeSeconds??0)/game.balance.attack.manualChargeSeconds),angle:Math.atan2(pos.y-game.player.y,pos.x-game.player.x)};}game.input.mouseDown=false;};canvas.onpointercancel=()=>{game.input.mouseDown=false;game.input.absorbHeld=false;};
function graph(){const c=$('graph'),g=c.getContext('2d');c.width=Math.max(300,c.clientWidth);c.height=150;g.fillStyle='#0f172a';g.fillRect(0,0,c.width,c.height);g.font='11px system-ui';for(const [y,label]of [[55,'100%'],[90,'50%'],[125,'0%']]){g.strokeStyle='#334155';g.beginPath();g.moveTo(35,y);g.lineTo(c.width-10,y);g.stroke();g.fillStyle='#94a3b8';g.fillText(label,1,y-3);}const draw=(samples,fn,color,dash=[])=>{if(!samples.length)return;g.strokeStyle=color;g.setLineDash(dash);g.beginPath();const maxT=Math.max(1,samples.at(-1).time);samples.forEach((s,i)=>{const x=35+s.time/maxT*(c.width-45),y=125-Math.max(0,Math.min(1,fn(s)))*70;i?g.lineTo(x,y):g.moveTo(x,y);});g.stroke();g.setLineDash([]);};const samples=game.samples,initial=game.entities.filter(e=>e.behavior==='ai').reduce((v,e)=>v+e.maxHp,0)||1;draw(samples,s=>s.playerHp/s.playerMaxHp,'#86efac');draw(samples,s=>s.targetHp/(s.targetMaxHp||initial),'#38bdf8');draw(samples,s=>s.progress,'#fbbf24');draw(samples,s=>s.damage/(s.targetMaxHp||initial),'#f87171');if(comparison)draw(comparison.runs.A.samples,s=>s.targetHp/(s.targetMaxHp||initial),'#fb923c',[5,4]);g.fillStyle='#e2e8f0';g.font='12px system-ui';g.fillText('초록: 내 HP · 파랑: 대상 HP · 노랑: 흡수 진행',10,16);g.fillText('빨강: 누적 피해/대상 최대 HP · 주황 점선: A 대상 HP',10,31);g.fillText(`${game.gameTime.toFixed(1)}초`,c.width-70,143);}
reset();let previous=performance.now(),lastGraph=0;function frame(now){const dt=Math.min(.15,(now-previous)/1000);previous=now;if(!game.paused&&!review.active){accumulator+=dt;while(accumulator>=1/60){game.update(1/60);accumulator-=1/60;if(game.gameOver){game.paused=true;break;}}}else accumulator=0;const rect=canvas.getBoundingClientRect();const w=Math.max(300,Math.round(rect.width)),h=Math.max(180,Math.round(rect.height));if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;game.viewZoom=Number($('zoom').value);game.updateCamera();game.render();const damage=game.entities.filter(e=>e.behavior==='ai').reduce((s,e)=>s+(e.damageReceived??0),0);$('stats').textContent=`${game.paused?'정지':'실행'} · ${game.gameTime.toFixed(2)}초 · 내 Size ${game.player.size.toFixed(1)} · HP ${Math.round(game.player.hp)}/${Math.round(game.player.maxHp)} · 누적 대상 피해 ${Math.round(damage)} · 객체 ${game.entities.length}`;if(now-lastGraph>=100){graph();lastGraph=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
