// R-META-002: use actual skill effects rather than species/slot guesses.
import {scaledSkill} from './skillCatalog.js';import {attackDamageForSize} from './combat.js?forest-composition-01';import {delta} from './topology.js';import {isHostile} from './collision.js';
export function influenceCoefficients({area,worldArea,affected=0,population=0,duration=1,cooldown=1,damageFraction=0,controlSeconds=0,sizeRatio=1}){
 const mapCoverage=Math.min(1,Math.max(0,area)/Math.max(1,worldArea)),objectCoverage=population>0?Math.max(0,Math.min(1,affected/population)):0,duty=Math.min(1,Math.max(0,duration)/Math.max(.001,cooldown)),severity=1-Math.exp(-Math.max(0,damageFraction)),sizeWeight=Math.sqrt(Math.max(.25,Math.min(4,sizeRatio))),control=Math.min(1,Math.max(0,controlSeconds)/Math.max(1,duration));
 return {mapCoverage,objectCoverage,duty,damageFraction,severity,sizeWeight,mapDominance:100*mapCoverage*duty,objectDominance:100*objectCoverage*duty,influence:100*objectCoverage*duty*(severity+(1-severity)*control),pressure:100*duty*(severity+(1-severity)*control)*sizeWeight};
}
export function skillFootprint(cfg){if(cfg.effect==='wave'||cfg.color==='blue'&&cfg.slot==='R'&&Number.isFinite(cfg.length)){const lanes=cfg.lanes??(cfg.slot==='R'?3:1);return {area:lanes*cfg.length*cfg.width,reach:cfg.length,upperBound:lanes>1};}const radius=cfg.radius??0,sector=cfg.effect==='chill'||cfg.effect==='ripple'||cfg.color==='cyan'&&cfg.slot==='R';return {area:Math.PI*radius*radius*(sector?1/3:1),reach:radius,sector,upperBound:false};}
export function analyzeSkill(game,owner,slot='R',point=owner){const cfg=scaledSkill(game.balance,owner,slot),shape=skillFootprint(cfg),dir=owner.facing??0,origin=owner.color==='yellow'&&slot==='R'?{...point,_world:game.balance.world}:owner,support=['shield','invite','muster','summon','vigor','dust'].includes(cfg.effect),actors=game.entities.filter(e=>e.alive&&['ai','player'].includes(e.behavior)&&e!==owner&&(cfg.effect==='vortex'||(support?!isHostile(owner,e):isHostile(owner,e)))),affected=actors.filter(e=>{const {x,y}=delta(origin,e),distance=Math.hypot(x,y);if(cfg.effect==='wave'||cfg.color==='blue'&&slot==='R'&&Number.isFinite(cfg.length))return (cfg.lanes===3||cfg.slot==='R'?[dir,dir-80*Math.PI/180,dir+80*Math.PI/180]:[dir]).some(a=>{const along=x*Math.cos(a)+y*Math.sin(a),across=-x*Math.sin(a)+y*Math.cos(a);return along>=0&&along<=cfg.length&&Math.abs(across)<=cfg.width/2;});return distance<=shape.reach&&(!shape.sector||Math.abs(Math.atan2(Math.sin(Math.atan2(y,x)-dir),Math.cos(Math.atan2(y,x)-dir)))<=Math.PI/3);});
 const duration=cfg.fieldDuration??cfg.waveDuration??cfg.freezeSeconds??cfg.buffDuration??cfg.shieldDuration??1,ticks=cfg.fieldDuration?Math.floor(cfg.fieldDuration/(cfg.tickInterval??1)):1,targetHp=Math.max(1,owner.size*5),damageFraction=support?0:cfg.hpFraction!=null?cfg.hpFraction*ticks:attackDamageForSize(owner.size,game.balance)*((cfg.damage??0)*ticks+(cfg.effect==='frost-burst'?(cfg.blastDamage??0)+(cfg.fieldDamage??0)*ticks:0))/targetHp;
 return {id:cfg.id,slot,name:cfg.name,support,size:owner.size,area:shape.area,areaUpperBound:shape.upperBound||shape.reach>Math.min(game.balance.world.worldWidth,game.balance.world.worldHeight)/2,affected:affected.length,population:actors.length,duration,cooldown:cfg.cooldown,controlSeconds:cfg.effect==='vortex'?duration:cfg.freezeSeconds??cfg.pushDuration??0,reference:cfg.effect==='vortex'?'all combatants in radius; suction duration is a control upper bound, not stun or measured discomfort':'nominal same-size target, before defense; representative geometry, not actual hit probability',...influenceCoefficients({area:shape.area,worldArea:game.balance.world.worldWidth*game.balance.world.worldHeight,affected:affected.length,population:actors.length,duration,cooldown:cfg.cooldown,damageFraction,controlSeconds:cfg.effect==='vortex'?duration:cfg.freezeSeconds??cfg.pushDuration??0,sizeRatio:1})};}
