import {SKILL_CATALOG,selectedSkill} from './skillCatalog.js';
import {SKILL_RULES,PRESET_STORAGE_KEY,applySkillPreset,defaultSkillPreset,skillPresetFromBalance} from './skillPreset.js';
export class SkillTuningUI {
 constructor(balance,parent){
  this.balance=balance;this.root=document.createElement('details');this.root.id='skill-tuning';const summary=document.createElement('summary');summary.textContent='E/R 스킬 후보 교체 · 수치 저장';this.root.append(summary);this.status=document.createElement('p');this.status.id='skill-preset-status';this.status.setAttribute('role','status');this.status.className='hint';this.root.append(this.status);const hint=document.createElement('p');hint.className='hint';hint.textContent='변경은 다음 시전부터 적용합니다. 비교할 때 같은 시드로 재시작하세요. 재사용 시간은 교체해도 초기화되지 않습니다.';this.root.append(hint);this.body=document.createElement('div');this.root.append(this.body);
  const actions=document.createElement('div');for(const [id,text,action]of [['skill-preset-save','이 기기에 저장',()=>{try{localStorage.setItem(PRESET_STORAGE_KEY,JSON.stringify(skillPresetFromBalance(balance)));this.status.textContent='이 기기에 저장했습니다. 다음 실행에도 적용됩니다.';}catch(e){this.status.textContent=`저장 실패: ${e.message}`;}}],['skill-preset-export','JSON 내보내기',()=>{try{const url=URL.createObjectURL(new Blob([JSON.stringify(skillPresetFromBalance(balance),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ball-next-skills.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.status.textContent='현재 설정을 내보냈습니다.';}catch(e){this.status.textContent=e.message;}}],['skill-preset-reset','기본값 복구',()=>{applySkillPreset(balance,defaultSkillPreset());try{localStorage.removeItem(PRESET_STORAGE_KEY);}catch{}this.render();this.status.textContent='기본값으로 복구했습니다. 저장한 설정도 해제했습니다.';}]]){const button=document.createElement('button');button.id=id;button.type='button';button.className='hud-btn';button.textContent=text;button.addEventListener('click',action);actions.append(button);}
  const label=document.createElement('label');label.textContent='JSON 불러오기 ';const file=document.createElement('input');file.type='file';file.accept='.json';file.id='skill-preset-import';file.addEventListener('change',async()=>{try{if(!file.files?.length)return;applySkillPreset(balance,JSON.parse(await file.files[0].text()));this.render();this.status.textContent='설정을 불러왔습니다. 다음 실행에도 쓰려면 이 기기에 저장하세요.';}catch(e){this.status.textContent=`불러오기 실패: ${e.message} 기존 설정은 유지됩니다.`;}finally{file.value='';}});label.append(file);actions.append(label);this.root.append(actions);parent.append(this.root);this.render();if(window.__skillPresetError)this.status.textContent=window.__skillPresetError;
 }
 numeric(label,value,rule,id,apply){const row=document.createElement('label');row.className='debug-row';const span=document.createElement('span');span.textContent=label;const input=document.createElement('input');input.type='number';input.value=value;input.min=rule.min;input.max=rule.max;input.step=rule.step??1;input.dataset.skillParam=id;input.addEventListener('change',()=>{const value=Number(input.value);if(input.value.trim()===''||!Number.isFinite(value)){this.status.textContent='유효한 숫자가 필요합니다.';return;}const n=Math.max(rule.min,Math.min(rule.max,value));input.value=n;const applied=apply(n);if(Number.isFinite(applied))input.value=applied;this.status.textContent='현재 실행에 적용했습니다. 다음 시전에 반영됩니다.';});row.append(span,input);return row;}
 render(){const b=this.balance;this.body.replaceChildren();for(const [id,label,value,rule,apply]of [['unlockSize','일반 E 해금 크기',b.abilitySkills?.unlockSize??100,{min:40,max:500},n=>{b.abilitySkills??={};b.abilitySkills.unlockSize=n;}],['territoryMultiplier','영역 추가 배율',b.abilitySkills?.territoryMultiplier??1,{min:.5,max:2,step:.1},n=>{b.abilitySkills??={};b.abilitySkills.territoryMultiplier=n;}],['attackTimingSizeScale','큰 몸 공격 시간 배율',b.combatScaling.attackTimingSizeScale??1,{min:.2,max:2,step:.05},n=>b.combatScaling.attackTimingSizeScale=n]])this.body.append(this.numeric(label,value,rule,id,apply));
  for(const color of b.colors)for(const slot of ['E','R']){const section=document.createElement('details');const title=document.createElement('summary');title.textContent=`${color.id} ${slot}`;section.append(title);const select=document.createElement('select');select.dataset.skillSlot=`${color.id}-${slot}`;for(const [id,cfg]of Object.entries(SKILL_CATALOG))if(cfg.color===color.id&&cfg.slot===slot){const option=document.createElement('option');option.value=id;option.textContent=cfg.name;select.append(option);}select.value=selectedSkill(b,color.id,slot).id;
   const fields=document.createElement('div'),draw=()=>{fields.replaceChildren();const cfg=selectedSkill(b,color.id,slot);for(const [key,rule]of Object.entries(SKILL_RULES))if(typeof cfg[key]==='number')fields.append(this.numeric(rule.label,cfg[key],rule,`${cfg.id}-${key}`,n=>{b.abilitySkills??={};b.abilitySkills.overrides??={};b.abilitySkills.overrides[cfg.id]??={};let value=key==='summonCount'?Math.floor(n):n;const current=selectedSkill(b,color.id,slot);if(key==='summonMinSize')value=Math.min(value,current.summonMaxSize);if(key==='summonMaxSize')value=Math.max(value,current.summonMinSize);b.abilitySkills.overrides[cfg.id][key]=value;return value;}));};select.addEventListener('change',()=>{b.abilitySkills??={};b.abilitySkills.loadout??={};b.abilitySkills.loadout[color.id]??={};b.abilitySkills.loadout[color.id][slot]=select.value;draw();this.status.textContent='후보를 교체했습니다. 다음 시전부터 사용합니다.';});section.append(select,fields);draw();this.body.append(section);}
 }
}
