const rule=(label,min,max,step)=>({label,min,max,step});
export const SKILL_RULES={
 apexWidth:rule('최상위 파도 폭',20,600,10),apexDamage:rule('최상위 피해 배율',.05,3,.05),
 nearDamageMultiplier:rule('근거리 피해 배율',1,2,.05),pullSpeed:rule('흡인 이동속도',20,600,10),
 visualRadiusMultiplier:rule('장막 표시 크기',1,5,.1),invulnerableSeconds:rule('무적(초)',.1,3,.1),
 shieldHpFraction:rule('보호막 HP 비율',.01,.5,.01),shieldDuration:rule('보호막(초)',1,20,1),blastDelay:rule('폭발 지연(초)',.2,5,.1),blastRadius:rule('폭발 반경',50,1500,20),blastDamage:rule('폭발 피해 배율',.05,3,.05),fieldDamage:rule('냉기 틱 피해 배율',.05,2,.05),freezeHitCount:rule('빙결 필요 타격',1,10,1),
 summonAttackInheritance:rule('소환 공격력 계승',0,1,.05),acceptChance:rule('수락 확률',0,1,.05),buffDefense:rule('방어력 추가',0,.5,.01),buffRegen:rule('초당 재생(최대HP 비율)',0,.05,.001),buffStackCap:rule('강화 중첩 상한',1,10,1),summonSizeVariation:rule('소환 크기 편차',0,.5,.05),summonSizeCapFraction:rule('소환 크기 상한 비율',.05,.2,.01),
 gatherDuration:rule('집결(초)',0,10,.5),summonRangeMultiplier:rule('소환 범위(오오라 배)',1,4,.1),absorbGuardSeconds:rule('흡수 면역(초)',0,8,.5),
 windup:rule('예고(초)',.1,3,.05),cooldown:rule('재사용(초)',2,60,1),radius:rule('반경',80,1500,20),castRange:rule('조준 거리',80,1500,20),length:rule('파도 길이',50,1500,20),width:rule('파도 폭',20,600,10),damage:rule('공격력 배율',.05,3,.05),freezeSeconds:rule('빙결(초)',.1,2,.05),pushDuration:rule('밀침(초)',.05,1,.05),pushSpeed:rule('밀침 속도',100,1000,50),waveDuration:rule('파도 진행(초)',.1,2,.1),commandDuration:rule('지시(초)',1,10,1),commandRadius:rule('지시 반경',80,1500,20),buffDuration:rule('강화(초)',1,60,1),buffDamage:rule('공격력 추가',0,1,.05),buffSpeed:rule('이동 배율',1,1.8,.05),buffRadius:rule('강화 반경',80,1500,20),summonCount:rule('소환 상한',0,3,1),summonAbsorbDelay:rule('소환 흡수 대기(초)',3,120,1),summonSizeFraction:rule('소환 크기 비율',.05,.2,.01),summonMinSize:rule('소환 최소 크기',20,100,5),summonMaxSize:rule('소환 최대 크기',40,150,5),fieldDuration:rule('장판(초)',1,30,1),tickInterval:rule('장판 간격(초)',.1,1,.05),hpFraction:rule('틱당 최대HP 비율',.01,.3,.01),missChance:rule('MISS 확률',0,.5,.05),
};
const object=value=>value&&typeof value==='object'&&!Array.isArray(value);
export function skillOverrides(id,raw,base){const out={};if(!object(raw)||!base)return out;for(const [key,value]of Object.entries(raw)){const r=SKILL_RULES[key];if(r&&typeof base[key]==='number'&&typeof value==='number'&&Number.isFinite(value)){let n=Math.max(r.min,Math.min(r.max,value));if(['summonCount','freezeHitCount'].includes(key))n=Math.floor(n);out[key]=n;}}if(out.summonMinSize> (out.summonMaxSize??base.summonMaxSize))out.summonMinSize=out.summonMaxSize??base.summonMaxSize;return out;}
