import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';
import {AIEntity} from '../js/ai.js';
import {startDodge,applyDamage} from '../js/combat.js';
import {nextSkillGoal} from '../js/progression.js';
function setup(color='cyan'){const g=createGame(11),p=g.player;p.color=color;p.size=120;p.attackState=p.dodgeState='READY';p.apex=true;p._specialApex=true;g.entities=[p];g.biomes.enabled=false;return {g,p};}
const tick=(g,n=60)=>{for(let i=0;i<n;i++)g.abilities.update(1/60);};
test('skill damage records actual lost HP including lethal respawn; export is independent',()=>{const {g,p}=setup(),t=new AIEntity({balance:g.balance,x:p.x+100,y:p.y,color:'red',colorHex:'#f00',startSize:40});t.hp=5;g.entities.push(t);g.abilities.start(p,0,null,null,'E');tick(g);const data=g.abilities.metrics.export(),row=data.rows[0];assert.equal(row.starts,1);assert.equal(row.fires,1);assert.equal(row.hits,1);assert.equal(row.damage,5);assert.equal(row.hpRatio,5/t.maxHp);assert.equal(data.pending,0);data.rows[0].damage=-1;assert.equal(g.abilities.metrics.export().rows[0].damage,5);const before=g.abilities.metrics.export().rows[0].damage;applyDamage(p,5,g,t,g.balance);assert.equal(g.abilities.metrics.export().rows[0].damage,before);});
test('dodge cancellation consumes cooldown and records exactly once without completion',()=>{const {g,p}=setup();g.abilities.start(p,0);startDodge(p,0,g.balance);g.abilities.metrics.reconcile();g.abilities.metrics.reconcile();const row=g.abilities.metrics.export().rows[0];assert.equal(row.starts,1);assert.equal(row.fires,0);assert.equal(row.cancelled,1);assert(p.specialCooldown>0);assert.equal(g.abilities.metrics.pending.size,0);});
test('wave damage remains attributed to its original R after owner changes candidate or dies',()=>{const {g,p}=setup('blue'),t=new AIEntity({balance:g.balance,x:p.x+100,y:p.y,color:'red',colorHex:'#f00',startSize:40});t.hp=t.maxHp=1000;g.entities.push(t);g.abilities.start(p,0);p.specialCast.directions=[0];tick(g,36);p.alive=false;g.abilities.release(p);tick(g,30);const row=g.abilities.metrics.export().rows[0];assert.equal(row.slot,'R');assert.equal(row.skill,'blue-trident');assert.equal(row.hits,1);assert(row.damage>0);assert.equal(row.cancelled,0);});
test('summon, buffs and recruits count effects without pretending to do direct damage',()=>{const {g,p}=setup('green');g.abilities.start(p,0);tick(g,30);const row=g.abilities.metrics.export().rows[0];assert.equal(row.fires,1);assert.equal(row.summons,2);assert(row.buffs>=3);assert.equal(row.damage,0);assert.equal(row.hits,0);assert.equal(g.runMetrics.export(g).skills.rows[0].summons,2);});
test('autoplay selects E while R cools down and does not combine slots in one action',()=>{const {g,p}=setup();p.specialCooldown=9;const t=new AIEntity({balance:g.balance,x:p.x+100,y:p.y,color:'red',colorHex:'#f00',startSize:50});g.entities.push(t);g.buildGrid();g.autoplay.setEnabled(true);g.autoplay.update(.1);assert.equal(g.autoplay.action.skillSlot,'E');assert(g.autoplay.action.special);g.updatePlayer(.01);assert.equal(p.specialCast.slot,'E');assert.equal(p.specialCooldown,9);p.specialCast=null;p.normalSkillCooldown=5;g.autoplay.update(.1);assert.equal(g.autoplay.action.special,false);p.specialCooldown=0;g.autoplay.update(.1);assert.equal(g.autoplay.action.skillSlot,'R');});
test('growth goal includes configurable E threshold and current apex cap',()=>{const {g,p}=setup();p.apex=false;p.size=110;g.balance.abilitySkills.unlockSize=150;assert.match(nextSkillGoal(p,g.balance).label,/E スキル|E 스킬/);p.size=150;g.balance.ecology.maxApex=7;assert.match(nextSkillGoal(p,g.balance).label,/상위 7위/);});

test('instant geometry diagnostics separate target escape, invalidation, invulnerability and caster travel without changing hits',()=>{
 const {g,p}=setup(),t=new AIEntity({balance:g.balance,x:p.x+100,y:p.y,color:'red',colorHex:'#f00',startSize:40});g.entities.push(t);g.abilities.start(p,0);p.x-=20;t.x+=500;tick(g,36);let row=g.abilities.metrics.export().rows[0];assert.equal(row.instantStarts,1);assert.equal(row.emptyInstantStarts,0);assert.equal(row.emptyInstantFires,1);assert.equal(row.escapedTargets,1);assert.equal(row.invalidatedTargets,0);assert.equal(row.originTravel,20);assert.equal(row.hits,0);
 p.specialCooldown=0;t.x=p.x+100;t.invincible=true;g.abilities.start(p,0);tick(g,36);row=g.abilities.metrics.export().rows[0];assert.equal(row.geometryTargets,1);assert.equal(row.invulnerableTargets,1);assert.equal(row.hits,0);
 p.specialCooldown=0;t.invincible=false;g.abilities.start(p,0);t.alive=false;tick(g,36);row=g.abilities.metrics.export().rows[0];assert.equal(row.invalidatedTargets,1);assert.equal(row.escapedTargets,1);assert.equal(row.instantFires,3);
});
test('instant diagnostics use minimum-image origin travel and exclude support or delayed damage skills',()=>{
 const {g,p}=setup();p.x=7990;g.abilities.start(p,0);p.x=10;tick(g,36);assert.equal(g.abilities.metrics.export().rows[0].originTravel,20);const other=setup('green');other.g.abilities.start(other.p,0);tick(other.g,30);assert.equal(other.g.abilities.metrics.export().rows[0].instantMeasured,false);
});
