import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';
import {AIEntity,decideAI,updateAI,recoveryDodgeAllowed,recoveryRetaliationAllowed} from '../js/ai.js';
import {dist} from '../js/collision.js';
test('an accepted recovery counter opportunity is consumed until the next actual hit',()=>{
 const ai={retaliateTimer:6,damageReceived:1},foe={},balance={ai:{recoveryRetaliationChance:.2}};let rolls=0;
 const roll=()=>{rolls++;return .1;};
 assert.equal(recoveryRetaliationAllowed(ai,foe,balance,roll),true);
 ai.retaliateTimer=5;
 assert.equal(recoveryRetaliationAllowed(ai,foe,balance,roll),false);
 assert.equal(rolls,1);
 ai.damageReceived=2;ai.retaliateTimer=6;
 assert.equal(recoveryRetaliationAllowed(ai,foe,balance,roll),true);assert.equal(rolls,2);
});
function setup(){const g=createGame(4),b=g.balance,a=new AIEntity({x:1000,y:1000,color:'blue',balance:b,startSize:100});g.entities=[a];g.biomes.enabled=true;g.biomes.danger=()=>null;g.biomes.regionAt=()=>({id:'snow'});g.biomes.blizzard=()=>true;g.biomes.sensingRange=()=>320;g.biomes.routePoint=(_,p)=>p;g.biomes.moveMultiplier=()=>1;g.era.warDecision=()=>false;g.buildGrid();const o={id:'refuge',candidate:'snow-shelter',x:1200,y:1000,config:{radius:70},_world:b.world};g.biomeObjects.objects=[o];return {g,b,a,o,run(){g.buildGrid();decideAI(a,g,b);}};}
test('snow refuge requires local snow/blizzard/enabled and stops at actual contact radius',()=>{const t=setup();t.run();assert.equal(t.a.state,'seek_refuge');const old=t.a.x;t.a.decisionTimer=10;updateAI(t.a,1,t.g,t.b);assert(t.a.x>old);assert(Math.abs(dist(t.a,t.o)-120)<1e-8);const x=t.a.x;updateAI(t.a,.1,t.g,t.b);assert.equal(t.a.x,x);t.g.biomes.regionAt=()=>({id:'forest'});t.run();assert.notEqual(t.a.state,'seek_refuge');t.g.biomes.regionAt=()=>({id:'snow'});t.g.biomes.blizzard=()=>false;t.run();assert.notEqual(t.a.state,'seek_refuge');t.g.biomes.blizzard=()=>true;t.g.biomes.enabled=false;t.run();assert.notEqual(t.a.state,'seek_refuge');});
test('recovering oasis outranks food but safety and normal-health collection stay unchanged',()=>{const t=setup();t.g.biomes.regionAt=()=>({id:'desert'});t.o.candidate='desert-oasis';t.a.hp=t.a.maxHp*.25;t.run();assert.equal(t.a.target,t.o);t.a.hp=t.a.maxHp*.7;t.run();assert.notEqual(t.a.state,'seek_refuge');t.a.hp=t.a.maxHp*.25;const foe=new AIEntity({x:1100,y:1000,color:'red',balance:t.b,startSize:150});t.g.entities.push(foe);t.run();assert.equal(t.a.state,'flee');assert.equal(t.a.target,foe);});
test('refuge object replacement invalidates stale target without alive flag',()=>{const t=setup();t.run();t.a.decisionTimer=10;t.g.biomeObjects.objects=[];updateAI(t.a,.01,t.g,t.b);assert.notEqual(t.a.state,'seek_refuge');assert.notEqual(t.a.target,t.o);});
test('refuge navigation follows shortest torus seam',()=>{const t=setup();const w=t.b.world;w.wrap=true;t.a.x=20;t.o.x=w.worldWidth-100;t.run();assert.equal(t.a.state,'seek_refuge');t.o.config.radius=10;t.a.decisionTimer=10;updateAI(t.a,.1,t.g,t.b);assert(t.a.x<20);});
test('recovering retaliation draws once per hit and preserves gates',()=>{const t=setup();t.g.biomes.blizzard=()=>false;t.a.hp=t.a.maxHp*.25;t.a.attackStack=2;t.b.ai.recoveryRetaliationChance=1;const foe=new AIEntity({x:1150,y:1000,color:'red',balance:t.b,startSize:100});t.g.entities.push(foe);t.a.retaliateTarget=foe;t.a.retaliateTimer=6;t.run();assert.equal(t.a.state,'chase_fight');t.a.attackStack=0;t.run();assert.notEqual(t.a.state,'chase_fight');let rolls=0;const a={retaliateTimer:6,damageReceived:1};assert(recoveryRetaliationAllowed(a,foe,t.b,()=>{rolls++;return 0;}));a.retaliateTimer=5;recoveryRetaliationAllowed(a,foe,t.b,()=>{rolls++;return 0;});assert.equal(rolls,1);a.damageReceived=2;a.retaliateTimer=6;recoveryRetaliationAllowed(a,foe,t.b,()=>{rolls++;return 0;});assert.equal(rolls,2);});
test('recovery dodge delays chosen fraction once per attack, not per frame',()=>{const b={ai:{recoveryDodgeDelayChance:1/3,recoveryDodgeReactionSeconds:.18}},a={},foe={attackState:'TELEGRAPH',attackTimer:0};let rolls=0;const draw=()=>{rolls++;return .1;};assert.equal(recoveryDodgeAllowed(a,foe,b,1,true,draw),false);foe.attackTimer=.1;assert.equal(recoveryDodgeAllowed(a,foe,b,1.1,true,draw),false);foe.attackState='CHARGING';foe.attackTimer=0;assert.equal(recoveryDodgeAllowed(a,foe,b,1.2,true,draw),true);assert.equal(rolls,1);foe.attackState='READY';recoveryDodgeAllowed(a,foe,b,2,false,draw);foe.attackState='TELEGRAPH';foe.attackTimer=0;assert.equal(recoveryDodgeAllowed(a,foe,b,3,true,draw),false);assert.equal(rolls,2);const fresh={};assert.equal(recoveryDodgeAllowed(fresh,foe,b,3,true,()=>.9),true);});
test('arrival uses existing continuous oasis healing, then recovery exit releases refuge',()=>{const t=setup();t.g.biomes.regionAt=()=>({id:'desert'});Object.assign(t.o,{candidate:'desert-oasis',config:{radius:70,effect:'heal',power:.08,cooldown:1}});t.g.biomeObjects.sync=()=>{};t.a.hp=t.a.maxHp*.25;t.run();t.a.decisionTimer=10;updateAI(t.a,1,t.g,t.b);t.g.buildGrid();const before=t.a.hp;t.g.biomeObjects.update(1);assert(t.a.hp>before);assert.equal(t.a.healVisualUntil,t.g.gameTime+.22);t.a.hp=t.a.maxHp*.6;t.run();assert.equal(t.a.recovering,false);assert.notEqual(t.a.state,'seek_refuge');});
test('arrival in shelter invokes existing exposure recovery and clears frost',()=>{const t=setup();t.o.config.effect='frost';t.g.biomeObjects.sync=()=>{};t.g.biomes.updateSandstorms=()=>{};t.g.biomes.snowEvent=Math.floor(t.g.gameTime/24);t.g.biomes.encounterTimer=10;t.a.frostExposure=6;t.a.frostbiteRemaining=1;t.run();t.a.decisionTimer=10;updateAI(t.a,1,t.g,t.b);assert(t.g.biomeObjects.inFrostShelter(t.a));t.g.biomes.update(.1);assert(t.a.frostExposure<6);assert.equal(t.a.frostbiteRemaining,0);});
test('refuge sensing sees nearby real outer range, but not objects beyond that edge',()=>{const t=setup();t.o.x=t.a.x+320+t.o.config.radius;t.run();assert.equal(t.a.state,'seek_refuge');t.o.x+=1;t.run();assert.notEqual(t.a.state,'seek_refuge');});
