import test from 'node:test';import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';import {AIEntity,decideAI,updateAI} from '../js/ai.js';import {applyDamage} from '../js/combat.js';import {isHostile,canAbsorb} from '../js/collision.js';import {startAbsorption,updateAbsorptions} from '../js/absorption.js';
function fixture(){const g=createGame(19);g.balance.era.warEntryChance=0;g.entities=['red','blue','green'].map((color,i)=>{const e=new AIEntity({balance:g.balance,x:4000+i*600,y:4000,startSize:400,color,colorHex:'#fff'});e.apex=true;e.role='predator';e.hp=e.maxHp=2000;return e;});g.gameTime=360;g.era.update(0);g.biomes.enabled=false;g.buildGrid();return {g,[Symbol.iterator]:function*(){yield g;yield* g.entities;}};}
test('one entry roll per apex per war; 0/100 percent presets and new cycle eligibility',()=>{const {g}=fixture();assert(g.entities.every(e=>!e.warTargets?.size));g.balance.era.warEntryChance=1;g.era.update(0);assert(g.entities.every(e=>!e.warTargets?.size));g.gameTime=480;g.era.update(0);g.gameTime=900;g.era.update(0);assert(g.entities.filter(e=>e.apex).every(e=>e.warTargets.size===1));assert.equal(g.era.warRolls.size,3);});
test('20 percent cumulative actual attack damage enlists a target and multiple wars coexist',()=>{const [g,a,b,c]=fixture();g.era.startWar(a,b);g.era.startWar(c,a);const hit=(attacker,target,ratio)=>applyDamage(target,target.size*.5+target.maxHp*ratio,g,attacker,g.balance,{knockback:false});hit(a,b,.1);assert(!b.warTargets?.has(a));hit(a,b,.1);assert(b.warTargets.has(a));hit(c,a,.19);assert(!a.warTargets.has(c));hit(c,a,.01);assert(a.warTargets.has(b)&&a.warTargets.has(c));assert(c.warTargets.has(a));assert.equal(g.era.warDamage.get(`${c.id}:${a.id}`),.2);});
test('war targets survive title loss, distance, low HP and target death until phase end',()=>{const [g,a,b]=fixture();g.era.startWar(a,b);a.apex=false;b.x=7000;a.hp=a.maxHp*.11;decideAI(a,g,g.balance);assert.equal(a.state,'chase_fight');assert.equal(a.target,b);a.hp=a.maxHp*.1;decideAI(a,g,g.balance);assert.equal(a.state,'flee');assert(a.warTargets.has(b));a.hp=a.maxHp*.3;decideAI(a,g,g.balance);assert.equal(a.state,'chase_fight');b.alive=false;assert(g.era.activeWar(a));g.gameTime=480;g.era.update(0);assert.equal(a.warTargets.size,0);assert.equal(g.era.activeWar(a),false);assert.equal(a.warCombat,false);});
test('war overrides low-health recovery and companion navigation but preserves active action timing',()=>{const [g,a,b,c]=fixture();g.allyLinks.recruit(a,c,true);g.era.startWar(a,b);a.hp=a.maxHp*.2;a.recovering=true;a.x=4000;b.x=6800;const before=a.x;updateAI(a,.1,g,g.balance);assert(a.x>before);assert.equal(a.state,'chase_fight');assert.equal(a.recovering,false);a.attackState='TELEGRAPH';const held=a.x;updateAI(a,.01,g,g.balance);assert.equal(a.x,held);});
test('same-color apex wars are combat, cannot be absorbed or linked, and damage enlists normally',()=>{const [g,a,b]=fixture();b.color=a.color;b.size=350;g.era.startWar(a,b);assert(isHostile(a,b));assert(!canAbsorb(a,b));assert(!g.allyLinks.connected(a,b));assert(!g.allyLinks.recruit(a,b));assert(applyDamage(b,1000,g,a,g.balance,{knockback:false}));assert(b.warTargets.has(a));});
test('invulnerability, misses and environmental damage never enlist a war opponent',()=>{const [g,a,b]=fixture();g.era.startWar(a,b);b.invincible=true;assert.equal(applyDamage(b,1000,g,a,g.balance),false);assert(!b.warTargets?.size);b.invincible=false;g.abilities.miss=()=>true;assert.equal(applyDamage(b,1000,g,a,g.balance),false);assert(!b.warTargets?.size);g.abilities.miss=()=>false;applyDamage(b,1000,g,a,g.balance,{kind:'field',knockback:false});assert(!b.warTargets?.size);});
test('absorption pays all cost during progress and refunds a quarter on success',()=>{const g=createGame(7),p=g.player;p.x=p.y=4000;p.color='blue';p.size=400;p.hp=p.maxHp=2000;p.allyAbsorptionEnabled=true;const t=new AIEntity({balance:g.balance,x:4000,y:4000,startSize:100,color:'blue',colorHex:'#00f'});g.entities=[p,t];startAbsorption(p,t,g.balance,g);const half=t.absorptionRequired/g.balance.absorption.maxAbsorptionSpeed/2;updateAbsorptions(g,half,g.balance);assert(Math.abs(t.absorptionHealthPaid-t.absorptionHealthCost*.5)<1e-8);updateAbsorptions(g,10,g.balance);assert(!t.alive);assert(Math.abs(t.absorptionHealthPaid-t.absorptionHealthCost)<1e-8);assert(Math.abs(t.absorptionHealthRecovered-t.absorptionHealthPaid*.25)<1e-8);});
test('absorption floor is one percent of max HP and never cancels or kills due to cost',()=>{const g=createGame(7),p=g.player;p.x=p.y=4000;p.color='blue';p.size=400;p.hp=30;p.maxHp=2000;p.allyAbsorptionEnabled=true;p.addGrowth=()=>{};const t=new AIEntity({balance:g.balance,x:4000,y:4000,startSize:100,color:'blue',colorHex:'#00f'});g.entities=[p,t];startAbsorption(p,t,g.balance,g);updateAbsorptions(g,10,g.balance);assert(!t.alive);assert(p.alive);assert.equal(p.hp,22.5);assert.equal(t.absorptionHealthPaid,10);});

test('default declaration chance is 80 percent and player autoplay respects the ten percent flee threshold',()=>{assert.equal(createGame(7).balance.era.warEntryChance,.8);const [g,a,b]=fixture();g.player=a;g.era.startWar(a,b);g.autoplay.setEnabled(true);a.hp=a.maxHp*.11;g.autoplay.update(0);assert(g.autoplay.action.move.x>0);a.hp=a.maxHp*.1;g.autoplay.timer=0;g.autoplay.update(0);assert(g.autoplay.action.move.x<0);});
test('at guard contact unavailable attack immediately retreats instead of holding its distance',()=>{const [g,a,b]=fixture();a.apex=b.apex=false;a.warTargets=new Set();a.size=200;b.size=400;b.x=a.x+300;a.state='flee';a.guardMode=true;a.target=b;a.attackStack=0;a.decisionTimer=10;const x=a.x;updateAI(a,.01,g,g.balance);assert(a.x<x);assert.equal(a.state,'flee');});
