import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';
import {BIOME_OBJECTS,DEFAULT_OBJECT_IDS,OBJECT_REGIONS,defaultObjectPreset,applyObjectPreset} from '../js/biomeObjectCatalog.js';
function setup(id){const g=createGame(7),p=g.player;g.entities=[p];g.biomes.enabled=true;const preset=defaultObjectPreset();preset.enabled=[id];preset.countPerType=1;applyObjectPreset(g.balance,preset);g.biomeObjects.sync();const o=g.biomeObjects.objects[0];p.x=o.x;p.y=o.y;p.hp=p.maxHp=1000;g.buildGrid();return {g,p,o};}
test('each biome has two active candidates, with three in the lake placed in its own biome deterministically',()=>{for(const region of Object.keys(OBJECT_REGIONS))assert.equal(DEFAULT_OBJECT_IDS.map(id=>BIOME_OBJECTS[id]).filter(c=>c.region===region).length,region==='lake'?3:2);const a=createGame(7),b=createGame(7);a.biomeObjects.sync();b.biomeObjects.sync();assert.equal(a.biomeObjects.objects.length,78);assert.deepEqual(a.biomeObjects.objects,b.biomeObjects.objects);for(const o of a.biomeObjects.objects)assert.equal(a.biomes.regionAt(o).id,o.config.region);});
test('invalid imports reject transactionally and settings are copied',()=>{const {g}=setup('grass-flowers'),p=defaultObjectPreset();p.overrides['grass-flowers']={growth:90};applyObjectPreset(g.balance,p);p.overrides['grass-flowers'].growth=1;assert.equal(g.balance.biomeObjects.overrides['grass-flowers'].growth,90);const before=JSON.stringify(g.balance.biomeObjects);for(const bad of [{...p,enabled:['missing']},{...p,countPerType:0},{...p,overrides:{'grass-flowers':{growth:NaN}}},{...p,overrides:JSON.parse('{"__proto__":{"power":0.1}}')}]){assert.throws(()=>applyObjectPreset(g.balance,bad));assert.equal(JSON.stringify(g.balance.biomeObjects),before);}});
test('food objects respect global cooldown, disabled candidates and orb capacity',()=>{const {g,o}=setup('grass-flowers');g.biomeObjects.update();assert.equal(g.entities.length,4);assert.equal(g.entities[1].growthValue,45);g.biomeObjects.update();assert.equal(g.entities.length,4);const p=defaultObjectPreset();p.enabled=[];applyObjectPreset(g.balance,p);g.biomeObjects.update();assert.equal(g.biomeObjects.objects.length,0);p.enabled=['grass-flowers'];p.countPerType=1;applyObjectPreset(g.balance,p);g.biomeObjects.update();assert.equal(g.entities.length,4);g.gameTime=o.config.cooldown;g.balance.spawning.maxOrbCount=4;g.biomeObjects.update();assert.equal(g.entities.length,5);});
test('objects require body contact and heal only wounded actors',()=>{const {g,p,o}=setup('lake-spring');g.biomeObjects.update();assert.equal(g.biomeObjects.events.length,0);p.hp=950;p.x=o.x+o.config.radius+p.size/2+1;g.buildGrid();g.biomeObjects.update();assert.equal(p.hp,950);p.x=o.x;g.buildGrid();g.biomeObjects.update();assert.equal(p.hp,1000);});
test('shield, speed, frost protection and volcanic cost apply to the touching actor',()=>{let {g,p}=setup('forest-tree');g.biomeObjects.update();assert.equal(p.shieldHp,80);assert.equal(p.shieldRemaining,6);({g,p}=setup('grass-windstone'));g.biomeObjects.update();assert.equal(g.abilities.speedMultiplier(p),1.25);g.gameTime=4;assert.equal(g.abilities.speedMultiplier(p),1);({g,p}=setup('snow-shelter'));g.biomeObjects.update();assert.equal(p.objectFrostResistance,.15);assert.equal(p.objectFrostUntil,8);({g,p}=setup('volcano-vent'));g.biomeObjects.update();assert.equal(p.hp,990);assert.equal(g.abilities.speedMultiplier(p),1.35);});
test('ice flowers double their food value during a blizzard',()=>{const {g}=setup('snow-flowers');g.gameTime=16;assert(g.biomes.blizzard());g.biomeObjects.update();assert.equal(g.entities[1].growthValue,130);});
