import test from 'node:test';import assert from 'node:assert/strict';import {createGame} from '../tools/headless.mjs';import {AIEntity} from '../js/ai.js';import {startAttack,updateAttack,applyDamage} from '../js/combat.js';import {absorptionHealthFraction,startAbsorption,updateAbsorptions} from '../js/absorption.js';import {scaledSkill} from '../js/skillCatalog.js';
function setup(){const g=createGame(7);g.entities=[];g.biomes.enabled=false;return g;}
const unit=(g,size=400,color='blue',x=4000)=>new AIEntity({balance:g.balance,x,y:4000,startSize:size,color,colorHex:'#00f'});
test('released manual attacks have no telegraph; minimal charge barely moves and full charge doubles damage',()=>{const g=setup(),p=g.player;p.size=400;p.apex=false;p.attackStack=10;startAttack(p,0,g.balance,0);const small=p.currentChargeDistance,weak=p.currentAttackPower;assert.equal(p.attackState,'CHARGING');assert.equal(p.currentTelegraphTime,0);assert.equal(small,18);assert.equal(weak,.35);startAttack(p,0,g.balance,.5);assert(p.currentChargeDistance>small);assert(Math.abs(p.currentAttackPower-1.175)<1e-8);startAttack(p,0,g.balance,1);assert.equal(p.currentChargeDistance,600);assert.equal(p.currentAttackPower,2);});
test('AI holds its charge before moving and releases without a second windup',()=>{const g=setup(),a=unit(g);startAttack(a,0,g.balance);const x=a.x;assert.equal(a.currentTelegraphTime,.675);updateAttack(a,.2,g.balance,[],g);assert.equal(a.x,x);updateAttack(a,.475,g.balance,[],g);assert.equal(a.attackState,'CHARGING');updateAttack(a,.1,g.balance,[],g);assert(a.x>x);});
test('healthy absorption curve gives 75 percent at near-equal size, 20 percent at half and 3 percent recovery when tiny',()=>{const g=setup(),a=unit(g);assert.equal(absorptionHealthFraction(a,unit(g,380),g.balance),.75);assert.equal(absorptionHealthFraction(a,unit(g,200),g.balance),.2);assert.equal(absorptionHealthFraction(a,unit(g,40),g.balance),-.03);const wounded=unit(g,380);wounded.hp=wounded.maxHp/2;assert.equal(absorptionHealthFraction(a,wounded,g.balance),.75*.75);});
test('real absorption retains large and medium health costs despite growth increasing capacity',()=>{for(const [size,fraction]of [[380,.75],[200,.2]]){const g=setup(),a=unit(g),b=unit(g,size);g.entities=[a,b];const hp=a.hp;startAbsorption(a,b,g.balance,g);updateAbsorptions(g,10,g.balance);assert(!b.alive);assert(a.size>400);assert(Math.abs(a.hp-hp*(1-fraction))<1e-8);assert(Math.abs(b.absorptionHealthPaid-hp*fraction)<1e-8);assert(a.hp>=a.maxHp*.01);}});
test('tiny ally absorption heals a wounded absorber by 3 percent of its starting max HP',()=>{const g=setup(),a=unit(g),b=unit(g,40);a.hp=1000;g.entities=[a,b];startAbsorption(a,b,g.balance,g);updateAbsorptions(g,10,g.balance);assert(!b.alive);assert.equal(a.hp,1060);assert.equal(b.absorptionHealthRecovered,60);assert.equal(b.absorptionHealthPaid,0);});
test('area and wave ranges increase between size100 and size200, not only after size350',()=>{const g=setup();for(const color of ['cyan','blue','green','red','yellow'])for(const slot of ['E','R']){const a=scaledSkill(g.balance,{color,size:100},slot),b=scaledSkill(g.balance,{color,size:200},slot);for(const k of ['radius','length','width','castRange','buffRadius'])if(a[k])assert(b[k]>a[k],`${color}/${slot}/${k}`);}});
test('apex prioritizes ready R and then E over available basic attacks even outside the old sensing radius',()=>{const g=setup(),a=unit(g,400,'cyan'),b=unit(g,400,'red',5000);a.apex=true;a.recovering=true;a.state='flee';g.entities=[a,b];g.buildGrid();assert(g.abilities.considerAI(a));assert.equal(a.specialCast.slot,'R');assert.equal(a.attackState,'READY');g.abilities.update(.6);b.x=4700;g.buildGrid();assert(g.abilities.considerAI(a));assert.equal(a.specialCast.slot,'E');});
test('support apex uses summon and invitation without needing a hostile enemy',()=>{const g=setup(),a=unit(g,400,'green');a.apex=true;g.entities=[a];g.buildGrid();assert(g.abilities.considerAI(a));assert.equal(a.specialCast.skill.effect,'summon');g.abilities.update(.5);assert.equal(g.entities.filter(e=>e.summoned).length,2);a.specialCooldown=0;g.buildGrid();assert(g.abilities.considerAI(a));assert.equal(a.specialCast.skill.effect,'invite');});
test('desert weather spawns in desert, drifts, expires and gives yellow resistance and real defense',()=>{const g=setup();g.biomes.enabled=true;g.biomes.sandstormTimer=0;g.biomes.updateSandstorms(0);const f=g.biomes.sandstorms[0];assert(f);assert.equal(g.biomes.regionAt(f).id,'desert');const x=f.x,y=f.y;g.biomes.updateSandstorms(1);assert(Math.abs(Math.hypot(f.x-x,f.y-y)-45)<1e-8);const blue=unit(g,100),yellow=unit(g,100,'yellow'),attacker=unit(g,100,'red');for(const e of [blue,yellow]){e.x=f.x;e.y=f.y;}g.entities=[blue,yellow,attacker];g.biomes.lavaAt=()=>null;g.biomes.damageTimer=0;const bh=blue.hp,yh=yellow.hp;g.biomes.update(.5);const blueLost=bh-blue.hp,yellowLost=yh-yellow.hp;assert(Math.abs(yellowLost/blueLost-.2)<1e-8);assert.equal(g.abilities.defenseMultiplier(yellow),1.25);const old=yellow.hp;applyDamage(yellow,150,g,attacker,g.balance,{knockback:false});assert.equal(old-yellow.hp,87.5);assert.equal(g.biomes.danger(yellow),null);g.biomes.updateSandstorms(f.remaining+.1);assert(!g.biomes.sandstorms.includes(f));assert.equal(g.abilities.defenseMultiplier(yellow),1);});
test('debug AI labels default off on each new run',()=>{const g=setup();assert.equal(g.showAILabels,false);g.showAILabels=true;g.reset();assert.equal(g.showAILabels,false);});
