import test from 'node:test';import assert from 'node:assert/strict';import {createGame} from '../tools/headless.mjs';import {AIEntity} from '../js/ai.js';import {applyDamage} from '../js/combat.js';import {scaledSkill,apexTerritoryRadius} from '../js/skillCatalog.js';
function fixture(){const g=createGame(7),p=g.player;p.x=p.y=4000;p.size=p.baseSize=400;p.hp=p.maxHp=2000;p.color='red';p.apex=true;p._specialApex=true;p.attackState=p.dodgeState='READY';g.entities=[p];g.biomes.enabled=false;return {g,p};}
function unit(g,x,color='red',size=100){return new AIEntity({balance:g.balance,x,y:4000,startSize:size,color,colorHex:'#f00'});}
test('desktop absorption toggle works without touch mode and right hold remains an alternative',()=>{const {g,p}=fixture();g.input.touchMode=false;g.input.absorbToggle=true;g.updatePlayer(0);assert(p.allyAbsorptionEnabled);g.input.absorbToggle=false;g.updatePlayer(0);assert(!p.allyAbsorptionEnabled);g.input.absorbHeld=true;g.updatePlayer(0);assert(p.allyAbsorptionEnabled);});
test('water reduces ordinary movement and blue keeps ninety percent speed',()=>{const {g,p}=fixture();g.biomes.enabled=true;g.biomes.regionAt=()=>({id:'lake'});g.input.keys.add('d');const x=p.x;g.updatePlayer(.1);assert(Math.abs(p.x-x-p.moveSpeed*.65*.1)<1e-8);p.color='blue';const blue=p.x;g.updatePlayer(.1);assert(Math.abs(p.x-blue-p.moveSpeed*.9*.1)<1e-8);g.biomes.regionAt=()=>({id:'grassland'});assert.equal(g.biomes.moveMultiplier(p),1);});
test('prolonged blizzard exposure causes DOT, cyan delays onset and size adds modest resistance',()=>{const {g,p}=fixture();g.biomes.enabled=true;g.biomes.regionAt=()=>({id:'snow'});const cyan=unit(g,p.x,'cyan',400);g.entities.push(cyan);g.gameTime=16;
 for(let i=0;i<10;i++){g.gameTime+=.5;g.biomes.update(.5);}
 assert(p.frostbiteRemaining>0);assert(p.hp<2000);assert.equal(cyan.frostbiteRemaining,0);assert(g.biomes.frostResistance(cyan)>g.biomes.frostResistance(p));assert(g.biomes.frostResistance({...p,size:600})>g.biomes.frostResistance({...p,size:40}));
 g.biomes.regionAt=()=>({id:'grassland'});for(let i=0;i<14;i++){g.gameTime+=.5;g.biomes.update(.5);}assert.equal(p.frostbiteRemaining,0);assert.equal(p.frostExposure,0);
});
test('snow tiles advertise an active blizzard even to a viewer outside the snow',()=>{const {g,p}=fixture();g.biomes.enabled=true;g.gameTime=17;const tile=g.biomes.tiles.find(t=>t.region.id==='snow');g.camera.x=tile.x+100;g.camera.y=tile.y+100;const grass=g.biomes.tiles.find(t=>t.region.id==='grassland');p.x=grass.x+100;p.y=grass.y+100;const labels=[],fills=[];const ctx=new Proxy({},{set(o,k,v){o[k]=v;return true;},get(o,k){if(k==='fillText')return t=>labels.push(t);if(k==='fillRect')return()=>fills.push(o.fillStyle);return o[k]??(()=>{});}});g.biomes.draw(ctx,1);assert(labels.some(t=>t.includes('눈보라')));assert(fills.includes('rgba(224,242,254,.22)'));assert.equal(g.biomes.playerSightRadius(),Infinity);});
test('red E produces real repeated damage without apex and respects allies, snapshot range and duration',()=>{const {g,p}=fixture();p.apex=false;const enemy=unit(g,4100,'blue',100),ally=unit(g,4100);g.entities.push(enemy,ally);const hp=enemy.hp,friend=ally.hp;assert(g.abilities.start(p,0,null,null,'E'));g.abilities.update(.25);assert.equal(g.abilities.embers.length,1);const radius=g.abilities.embers[0].radius;g.balance.abilitySkills.overrides={'red-embers':{radius:80}};g.abilities.update(.5);assert(enemy.hp<hp);assert.equal(ally.hp,friend);assert.equal(g.abilities.embers[0].radius,radius);g.abilities.update(6);assert.equal(g.abilities.embers.length,0);const rows=g.abilities.metrics.export().rows;assert(rows.some(r=>r.skill==='red-embers'&&r.damage>0));});
test('red R recruits all aura allies, gathers then follows caster attacks and attackers with buffs',()=>{const {g,p}=fixture();const allies=Array.from({length:7},(_,i)=>unit(g,4100+i*100)),far=unit(g,6000),enemy=unit(g,4300,'blue',400),attacker=unit(g,4400,'green',400);g.entities.push(...allies,far,enemy,attacker);assert(g.abilities.start(p,0,null,null,'R'));g.abilities.update(.6);const r=g.abilities.musters[0];assert.equal(r.recipients.size,8);assert.equal(far.command,undefined);assert.equal(allies[0].command.kind,'muster');assert.equal(p.command,undefined);assert.equal(g.abilities.speedMultiplier(allies[0]),1.25);assert(g.abilities.damageMultiplier(allies[0])>=1.3);assert.equal(scaledSkill(g.balance,p,'R').radius,apexTerritoryRadius(p,g.balance));assert(g.abilities.commandDecision(allies[0]));assert.equal(allies[0].state,'command_move');applyDamage(enemy,300,g,p,g.balance,{knockback:false});applyDamage(p,300,g,attacker,g.balance,{knockback:false});assert(r.targets.has(enemy)&&r.targets.has(attacker));g.abilities.update(3);assert(g.abilities.commandDecision(allies[0]));assert.equal(allies[0].state,'chase_fight');assert([enemy,attacker].includes(allies[0].target));g.gameTime+=12;g.abilities.update(12);assert.equal(g.abilities.musters.length,0);assert.equal(g.abilities.speedMultiplier(allies[0]),1);assert.equal(allies[0].command,null);});
test('muster cancels on title loss and turns hostile allies out of the buff',()=>{const {g,p}=fixture(),a=unit(g,4100);g.entities.push(a);g.abilities.start(p,0,null,null,'R');g.abilities.update(.6);g.gameTime=360;g.balance.era.warEntryChance=0;g.era.update(0);g.era.startWar(p,a);assert.equal(g.abilities.speedMultiplier(a),1);p.apex=false;g.abilities.update(.1);assert.equal(g.abilities.musters.length,0);assert.equal(a.command,null);});
