import test from 'node:test';import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';import {AIEntity,decideAI,updateAI} from '../js/ai.js';import {startAbsorption,updateAbsorptions} from '../js/absorption.js';import {attackChargeDurationForSize,attackTelegraphTimeForSize} from '../js/combat.js';
function fixture(){const g=createGame(7),p=g.player;p.x=p.y=4000;p.size=400;p.hp=p.maxHp=2000;p.color='green';g.entities=[p];g.biomes.enabled=false;g.autoplay.setEnabled(false);return {g,p};}
test('guard retreats from a larger nearby threat, continues retreat and counterattacks when pursued',()=>{const {g,p}=fixture();p.color='red';const a=new AIEntity({balance:g.balance,x:4320,y:4000,startSize:200,color:'blue',colorHex:'#00f'});a.personality='cautious';g.entities.push(a);g.buildGrid();decideAI(a,g,g.balance);assert(a.guardMode);assert.equal(a.state,'flee');const x=a.x;updateAI(a,.1,g,g.balance);assert(a.x>x);a.x=4450;a.decisionTimer=10;const held=a.x;updateAI(a,.1,g,g.balance);assert(a.x>held);a.x=4300;g.gameTime=10;g.buildGrid();decideAI(a,g,g.balance);assert.equal(a.state,'chase_fight');});
test('large attack timing is capped gently and manual full charge is shorter',()=>{const {g}=fixture();assert(attackTelegraphTimeForSize(400,g.balance)<.6);assert(attackChargeDurationForSize(600,g.balance)<.7);assert.equal(g.balance.attack.manualChargeSeconds,.9);});
test('activating absorption leaves a formation and progressive cost scales with target health',()=>{const {g,p}=fixture();const a=new AIEntity({balance:g.balance,x:4000,y:4000,startSize:100,color:'green',colorHex:'#0f0'});g.entities.push(a);g.allyLinks.recruit(p,a);g.input.absorbHeld=true;g.updatePlayer(0);assert(!p.companionGroup);startAbsorption(p,a,g.balance,g);assert(Math.abs(a.absorptionHealthCost-2000*(.23*.1/.35-.03))<1e-8);updateAbsorptions(g,.1,g.balance);assert(p.hp<2000);assert.equal(p.regenTimer,0);const before=p.hp;g.input.absorbHeld=false;g.updatePlayer(0);updateAbsorptions(g,.1,g.balance);assert.equal(p.hp,before);a.hp=a.maxHp*.5;startAbsorption(p,a,g.balance,g);assert(Math.abs(a.absorptionHealthCost-2000*(.23*.1/.35-.03)*.6)<1e-8);p.hp=1;p.allyAbsorptionEnabled=true;updateAbsorptions(g,1,g.balance);assert.equal(a.alive,false);assert(p.alive&&p.hp>=p.maxHp*.01);});
test('all wrapped terrain copies render before any entity copy',()=>{const {g,p}=fixture();g.biomes.enabled=true;p.x=g.camera.x=0;p.y=g.camera.y=0;g.camera.zoom=1;g.ctx=new Proxy({},{get:()=>()=>{}});const order=[];g.biomes.draw=()=>order.push('terrain');g.drawEntities=()=>order.push('entity');for(const name of ['drawGrid','drawTerritories','drawAbsorptionLinks','drawParticles','drawFloatingTexts','drawTouchAim','drawNames'])g[name]=()=>{};for(const owner of [g.era,g.relics,g.abilities,g.allyLinks])owner.draw=()=>{};g.biomes.drawBlizzardOverlay=()=>{};g.render();assert(order.filter(x=>x==='terrain').length>1);assert(order.lastIndexOf('terrain')<order.indexOf('entity'));});

test('large threat sensing includes the body surface beyond the old center-distance limit',()=>{const {g,p}=fixture();p.size=600;p.color='red';const a=new AIEntity({balance:g.balance,x:4500,y:4000,startSize:200,color:'blue',colorHex:'#00f'});g.entities.push(a);g.buildGrid();decideAI(a,g,g.balance);assert.equal(a.guardMode,true);assert.equal(a.target,p);});
