import test from 'node:test';import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';import {AIEntity,decideAI} from '../js/ai.js';import {startAbsorption,cancelAbsorption,updateAbsorptions,resistanceTimeFor,maintainDistanceFor} from '../js/absorption.js';import {applyDamage} from '../js/combat.js';import {spawnOrb} from '../js/spawning.js';import {applyObjectPreset,defaultObjectPreset} from '../js/biomeObjectCatalog.js';import {growthRewardFor} from '../js/entity.js';
function fixture(size=700,color='blue'){const g=createGame(7),p=g.player;p.size=p.baseSize=size;p.x=p.y=4000;p.color=color;p.hp=p.maxHp=4000;p.allyAbsorptionEnabled=true;p.apex=false;g.entities=[p];g.biomes.enabled=false;return {g,p};}
function unit(g,size=650,color='blue',x=4000){const t=new AIEntity({balance:g.balance,x,y:4000,startSize:size,color,colorHex:'#60a5fa'});t.hp=t.maxHp=4000;g.entities.push(t);return t;}
test('R-ABS-010 cancellation restores only paid HP in proportion to decaying progress and cannot refund twice',()=>{const {g,p}=fixture(),t=unit(g);startAbsorption(p,t,g.balance,g);updateAbsorptions(g,.4,g.balance);const paid=t.absorptionHealthPaid,progress=t.absorptionProgress;applyDamage(p,100,g,null,g.balance,{kind:'field',ignoreDefense:true});const after=p.hp;cancelAbsorption(t);assert.equal(p.hp,after);updateAbsorptions(g,.3,g.balance);assert(Math.abs(p.hp-after-paid/2)<1e-8);assert(Math.abs(t.absorptionProgress-progress/2)<1e-8);updateAbsorptions(g,.3,g.balance);assert(Math.abs(p.hp-(4000-100))<1e-8);cancelAbsorption(t);updateAbsorptions(g,1,g.balance);assert(Math.abs(p.hp-3900)<1e-8);});
test('R-ABS-008 size700 can start and finish absorbing size650 at body contact; wounded allies finish sooner with less HP spent',()=>{const results=[];for(const hp of [1,.25]){const {g,p}=fixture(),t=unit(g,650,'blue',4675);t.hp=t.maxHp*hp;g.buildGrid();g.resolveConsumption();assert.equal(t.beingAbsorbedByRef,p);assert(maintainDistanceFor(p,g.balance,t)>=675);let seconds=0;while(t.alive&&seconds<10){updateAbsorptions(g,1/60,g.balance);seconds+=1/60;}assert(!t.alive);results.push({seconds,paid:t.absorptionHealthPaid});}assert(results[1].seconds<results[0].seconds*.5);assert(results[1].paid<results[0].paid*.5);});
test('R-ABS-011 blue suction is stronger than other colors and force above one never makes positions NaN',()=>{const distances=[];for(const color of ['red','blue']){const {g,p}=fixture(700,color),t=unit(g,650,color,4400);startAbsorption(p,t,g.balance,g);updateAbsorptions(g,.1,g.balance);assert(Number.isFinite(t.x));distances.push(t.x-p.x);}assert(distances[1]<distances[0]);});
test('R-WORLD-004 frost gauge delays onset, persists while draining and shelter immediately cures then reduces exposure',()=>{const {g,p}=fixture(40,'red');g.biomes.enabled=true;g.biomes.regionAt=()=>({id:'snow'});g.biomes.blizzard=()=>true;g.biomes.lavaAt=()=>null;g.biomes.sandstormAt=()=>false;g.biomeObjects.inFrostShelter=()=>false;g.biomes.update(5);assert.equal(p.frostbiteRemaining,0);g.biomes.update(1);assert(p.frostbiteRemaining>0);g.biomes.blizzard=()=>false;g.biomes.update(.5);assert(p.frostbiteRemaining>0);assert.equal(p.frostExposure,5);g.biomes.update(2.5);assert.equal(p.frostbiteRemaining,0);g.biomes.blizzard=()=>true;g.biomes.update(6);g.biomeObjects.inFrostShelter=()=>true;g.biomes.update(.1);assert.equal(p.frostbiteRemaining,0);assert(p.frostExposure<6);});
test('R-WORLD-004 real shelter cures every contacting actor even while its pickup cooldown is active',()=>{const {g,p}=fixture(),t=unit(g);g.biomes.enabled=true;const cfg=defaultObjectPreset();cfg.enabled=['snow-shelter'];cfg.countPerType=1;applyObjectPreset(g.balance,cfg);g.biomeObjects.sync();const o=g.biomeObjects.objects[0];for(const e of [p,t]){e.x=o.x;e.y=o.y;e.frostExposure=6;e.frostbiteRemaining=1;}g.biomeObjects.cooldowns.set(o.id,100);g.biomes.blizzard=()=>true;g.biomes.update(.1);assert.equal(p.frostbiteRemaining,0);assert.equal(t.frostbiteRemaining,0);});
test('R-ABIL-004 normal E launches one straight wave, apex E three with a shared hit registry, near hits deal more',()=>{for(const apex of [false,true]){const {g,p}=fixture(100);p.apex=apex;p._specialApex=apex;const t=unit(g,100,'red',4050),far=unit(g,100,'red',4350),behind=unit(g,100,'red',3950);g.buildGrid();assert(g.abilities.start(p,0,null,null,'E'));const dirs=p.specialCast.directions;assert.equal(dirs.length,apex?3:1);g.abilities.update(.3);assert.equal(g.abilities.waves.length,apex?3:1);if(apex)assert.equal(g.abilities.waves[0].hit,g.abilities.waves[1].hit);g.abilities.update(.5);assert(4000-t.hp>4000-far.hp);assert(far.hp<4000);if(!apex)assert.equal(behind.hp,4000);}});
test('R-ABIL-005 blue R pulls allies enemies and food with stronger movement near the caster',()=>{const {g,p}=fixture(100);p.apex=true;p._specialApex=true;const near=unit(g,40,'red',4100),far=unit(g,40,'blue',4300),orb=spawnOrb(g.balance,{x:4200,y:4000});g.entities.push(orb);g.buildGrid();g.abilities.fire(p,{slot:'R',id:1,dir:0,point:{x:p.x,y:p.y},skill:g.abilities.skill(p,'R')});const initial=[near.x,far.x,orb.x];g.abilities.update(.1);assert(initial[0]-near.x>initial[1]-far.x);assert(orb.x<initial[2]);assert.equal(p.x,4000);});
test('R-AI-010 struck AI immediately prioritizes aggressor over food and keeps six second memory',()=>{const {g,p}=fixture(100,'red'),a=unit(g,100,'blue',4150),other=unit(g,100,'yellow',4160);g.buildGrid();applyDamage(a,50,g,p,g.balance,{knockback:false});decideAI(a,g,g.balance);assert.equal(a.target,p);assert.equal(a.state,'chase_fight');assert.equal(a.retaliateTimer,6);assert.equal(a.decisionTimer,0);});
test('R-GROWTH-007 half pace applies once to every common reward at every size',()=>{const {g}=fixture();for(const size of [20,100,400,600,1500]){g.balance.growth.paceMultiplier=1;const old=growthRewardFor(100,{size},g.balance);g.balance.growth.paceMultiplier=.5;assert.equal(growthRewardFor(100,{size},g.balance),old*.5);}});
test('R-META-005 idle attacks do not query spatial targets while charging still hits nearby enemies',()=>{const {g,p}=fixture();let scans=0;const query=g.getNearbyEntities.bind(g);g.getNearbyEntities=(...args)=>{scans++;return query(...args);};p.attackState='READY';assert.deepEqual(g.hostileTargetsFor(p),[]);assert.equal(scans,0);unit(g,600,'red',4500);g.buildGrid();p.attackState='CHARGING';assert.equal(g.hostileTargetsFor(p).length,1);assert.equal(scans,1);});
test('R-ABS-010 target death and world removal retain cancellation refund without healing a later player life',()=>{const {g,p}=fixture(),t=unit(g);startAbsorption(p,t,g.balance,g);updateAbsorptions(g,.2,g.balance);const paid=t.absorptionHealthPaid;g.onEntityDeath(t,null);t.alive=false;g.entities=[p];const hp=p.hp;updateAbsorptions(g,.6,g.balance);assert(Math.abs(p.hp-hp-paid)<1e-8);const t2=unit(g);startAbsorption(p,t2,g.balance,g);updateAbsorptions(g,.2,g.balance);cancelAbsorption(t2);p.defeatSerial=1;p.hp=100;updateAbsorptions(g,.6,g.balance);assert.equal(p.hp,100);});
test('R-ABS-008 active size600 and size1000 AI can dodge while an ordinary moving player pursues and finishes absorption',()=>{for(const size of [600,1000]){const {g,p}=fixture(size),t=unit(g,size*.95,'blue',4000+size*.975);p._recomputeStacks(g.balance,false);g.abilities.enabled=false;g.enemySpawnLoop=()=>{};g.orbSpawnLoop=()=>{};g.input.absorbToggle=true;g.input.touchMode=true;g.input.consumeDodge=()=>t.dodgeState==='DODGING';for(let i=0;i<600&&t.alive;i++){const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy);g.input.touchMove={x:dx/Math.max(1,d),y:dy/Math.max(1,d)};g.update(1/60);}assert(!t.alive);assert.equal(t.dodgeStack,0);assert(g.gameTime<5);}});
test('R-ABIL-005 suction ends when its owner loses apex and R-META-002 influence measures circle geometry without NaN',async()=>{const {analyzeSkill}=await import('../js/skillInfluence.js'),{g,p}=fixture(100);p.apex=true;p._specialApex=true;unit(g,40,'blue',4100);unit(g,40,'red',4200);g.buildGrid();const info=analyzeSkill(g,p,'R');assert.equal(info.affected,2);assert.equal(info.damageFraction,0);assert(Number.isFinite(info.area));assert(info.influence>0);g.abilities.fire(p,{slot:'R',id:1,dir:0,point:{x:p.x,y:p.y},skill:g.abilities.skill(p,'R')});assert.equal(g.abilities.vortices.length,1);g.abilities.loseApex(p);assert.equal(g.abilities.vortices.length,0);});
test('R-ABIL-005 large blue AI and autoplay use actual suction radius beyond old default wave length',()=>{const {g,p}=fixture(600),t=unit(g,500,'red',4900);p.apex=p._specialApex=true;g.buildGrid();assert(g.abilities.canAffect(p,t,'R'));assert(g.abilities.considerAI(p));assert.equal(p.specialCast.skill.id,'blue-vortex');});
