import test from 'node:test';import assert from 'node:assert/strict';import {createGame} from '../tools/headless.mjs';import {applyObjectPreset,defaultObjectPreset,normalizeObjectPreset,BIOME_OBJECTS} from '../js/biomeObjectCatalog.js';import {applyDamage} from '../js/combat.js';import {spawnOrb} from '../js/spawning.js';import {objectRole} from '../js/biomeObjects.js';import {delta} from '../js/topology.js';
function setup(id){const g=createGame(7),p=g.player;g.entities=[p];g.biomes.enabled=true;const cfg=defaultObjectPreset();cfg.enabled=[id];cfg.countPerType=1;applyObjectPreset(g.balance,cfg);g.biomeObjects.sync();const o=g.biomeObjects.objects[0];p.x=o.x;p.y=o.y;p.hp=p.maxHp=1000;g.buildGrid();return {g,p,o};}
test('flower and shell decorations boost invitation acceptance until expiry',()=>{for(const id of ['grass-garland','lake-garland']){const {g,p,o}=setup(id),before=g.allyLinks.acceptChance(p,{});g.biomeObjects.update();assert.equal(g.allyLinks.acceptChance(p,{}),before+o.config.power);assert.equal(p.companionDecoration,id==='lake-garland'?'shell':'flower');g.gameTime=o.config.duration;assert.equal(g.allyLinks.acceptChance(p,{}),before);}});
test('three wind stones grant a fifteen-second boost and consume stacks',()=>{const {g,p,o}=setup('grass-wind-stack');for(let i=0;i<3;i++){g.gameTime=i*o.config.cooldown;g.biomeObjects.update();if(i<2){assert.equal(p.windStoneStacks,i+1);assert.equal(g.abilities.speedMultiplier(p),1);}}assert.equal(p.windStoneStacks,0);assert.equal(g.abilities.speedMultiplier(p),1.35);g.gameTime+=15;assert.equal(g.abilities.speedMultiplier(p),1);});
test('obsidian shield actually absorbs damage and attack/defense bonuses disappear when depleted',()=>{const {g,p,o}=setup('volcano-obsidian-stack');for(let i=0;i<3;i++){g.gameTime=i*o.config.cooldown;g.biomeObjects.update();}assert.equal(p.obsidianShieldHp,120);assert.equal(g.abilities.damageMultiplier(p),1.08);assert.equal(g.abilities.defenseMultiplier(p),1.08);applyDamage(p,80,g,null,g.balance,{kind:'field',ignoreDefense:true});assert.equal(p.hp,1000);assert.equal(p.obsidianShieldHp,40);applyDamage(p,60,g,null,g.balance,{kind:'field',ignoreDefense:true});assert.equal(p.hp,980);assert.equal(p.obsidianShieldHp,0);assert.equal(g.abilities.damageMultiplier(p),1);assert.equal(g.abilities.defenseMultiplier(p),1);});
test('berries periodically spawn without contact and healing pickup restores HP without growth',()=>{const {g,p,o}=setup('forest-berry-grove');p.x=1000;p.y=1000;g.buildGrid();g.biomeObjects.update();assert.equal(g.entities.length,6);const heal=g.entities.find(e=>e.healFraction);assert(heal);assert.equal(heal.growthValue,0);g.biomeObjects.update();assert.equal(g.entities.length,6);g.gameTime=o.config.cooldown;g.biomeObjects.update();assert.equal(g.entities.length,11);p.x=heal.x;p.y=heal.y;p.hp=600;g.entities=[p,heal];g.buildGrid();const size=p.size,growth=p.growth;g.resolveConsumption();assert.equal(p.hp,680);assert.equal(p.size,size);assert.equal(p.growth,growth);assert(!heal.alive);});
test('vent is harmless while resting and applies paced damage to every contacting actor during eruption',()=>{const {g,p}=setup('volcano-vent-cycle');const other={...p,id:p.id+100,behavior:'ai'};g.entities.push(other);g.buildGrid();g.gameTime=5;g.biomeObjects.update();assert.equal(p.hp,1000);g.gameTime=12;g.biomeObjects.update();const hp=p.hp;assert(hp<1000);assert.equal(other.hp,hp);g.biomeObjects.update();assert.equal(p.hp,hp);g.gameTime=12.5;g.biomeObjects.update();assert(p.hp<hp);assert.equal(objectRole(BIOME_OBJECTS['volcano-vent-cycle']),'danger');});
test('lake current has connected lake-only paths and carries both actors and food',()=>{const {g,p,o}=setup('lake-current');for(const point of o.points)assert.equal(g.biomes.regionAt(point).id,'lake');const a={...o.points[0],_world:g.balance.world},v=delta(a,o.points[1]);p.x=a.x+v.x*.25;p.y=a.y+v.y*.25;p.size=20;const orb=spawnOrb(g.balance,{x:p.x,y:p.y});g.entities.push(orb);g.buildGrid();const from={x:p.x,y:p.y,_world:g.balance.world},food={x:orb.x,y:orb.y,_world:g.balance.world};g.biomeObjects.update(.5);const actorDrift=Math.hypot(...Object.values(delta(from,p)));assert(actorDrift>0);assert(actorDrift<=p.moveSpeed*g.biomes.moveMultiplier(p)*.25*.5+1e-6);assert(Math.hypot(...Object.values(delta(food,orb)))>49);});
test('vortex draws objects inward without overshooting the center or inflicting direct damage',()=>{const {g,p,o}=setup('lake-vortex');p.x=o.x+100;g.buildGrid();g.biomeObjects.update(.5);assert(p.x<o.x+100&&p.x>=o.x);assert.equal(p.hp,1000);});
test('v1 choices migrate to new effects, archives stay selectable and incompatible settings reject atomically',()=>{const raw={format:'ball-next-objects-v1',countPerType:1,enabled:['grass-flowers','lake-spring'],overrides:{'grass-flowers':{growth:99}}},p=normalizeObjectPreset(raw);assert.deepEqual(p.enabled,['grass-garland','lake-current','lake-vortex']);assert.equal(p.overrides['grass-flowers'].growth,99);assert.equal(p.format,'ball-next-objects-v3');const {g}=setup('forest-tree'),before=JSON.stringify(g.balance.biomeObjects),bad=defaultObjectPreset();bad.overrides={'volcano-vent-cycle':{activeDuration:12}};assert.throws(()=>applyObjectPreset(g.balance,bad));assert.equal(JSON.stringify(g.balance.biomeObjects),before);});
