import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';
import {AIEntity} from '../js/ai.js';
import {growthFromSize} from '../js/entity.js';
import {assessGameplay} from '../js/gameplayEvaluation.js';
import {realizedGrowthWindow} from '../js/opportunityChannels.js';
import {minimumDeathDropGrowth,spawnDeathOrbs} from '../js/spawning.js';
import {BalanceMetrics} from '../js/balanceMetrics.js';
import {resetRandom,random} from '../js/random.js';
function setup(){const g=createGame(7),p=g.player;p.addGrowth(growthFromSize(200,p.baseSize,g.balance.growth.growthToSizeRatio,g.balance.growth),g.balance);g.biomes.enabled=false;g.entities=[p];g.allyLinks.groups.clear();p.companionGroup=null;p.hp=p.maxHp;return {g,p};}
const unit=(g,p,color,size=100,x=80)=>new AIEntity({balance:g.balance,x:p.x+x,y:p.y,color,colorHex:'#f00',startSize:size});
test('nearby absorbable body is a potential opportunity even with no food; grouping removes it',()=>{const {g,p}=setup(),t=unit(g,p,p.color);g.entities.push(t);g.buildGrid();const a=assessGameplay(g);assert.equal(a.growthOpportunity,false);assert.equal(a.opportunityChannels.absorption,true);assert(a.opportunityChannels.absorptionGain>0);p.companionGroup=1;assert.equal(assessGameplay(g).opportunityChannels.absorption,false);});
test('healthy actor may hunt a smaller hostile; low health and rewardless summons do not count',()=>{const {g,p}=setup(),color=g.balance.colors.find(c=>c.id!==p.color).id,t=unit(g,p,color);t.attackUnlocked=false;g.entities.push(t);g.buildGrid();let a=assessGameplay(g);assert(a.opportunityChannels.hunt);assert(a.opportunityChannels.huntEstimatedSeconds>0);p.hp=p.maxHp*.3;assert.equal(assessGameplay(g).opportunityChannels.hunt,false);p.hp=p.maxHp;t.summoned={owner:p,expires:10};assert.equal(assessGameplay(g).opportunityChannels.hunt,false);});
test('forecast is conservative about other nearby threats and consumes no simulation RNG',()=>{const {g,p}=setup(),color=g.balance.colors.find(c=>c.id!==p.color).id,t=unit(g,p,color),threat=unit(g,p,color,300,120);g.entities.push(t,threat);g.buildGrid();resetRandom(42);const expected=random('world');resetRandom(42);const before=JSON.stringify(g.snapshot()),a=assessGameplay(g);assert.equal(a.opportunityChannels.hunt,false);assert.equal(random('world'),expected);assert.equal(JSON.stringify(g.snapshot()),before);});
test('reward bound cannot exceed actual random drop and keeps direct payout separate',()=>{const {g,p}=setup(),t=unit(g,p,'red',120);t.addGrowth(5000,g.balance);const lower=minimumDeathDropGrowth(t,g.balance),actual=spawnDeathOrbs(t,g.balance).reduce((n,o)=>n+o.growthValue,0);assert(lower>=t.size*g.balance.killReward.growthPerSize);assert(actual+1e-8>=lower);});
test('actual growth window distinguishes missing history, zero growth and life boundary',()=>{const history=[{time:0,size:100,defeats:0},{time:3,size:101,defeats:0}],current={time:5,size:105,defeats:0,growthNeeded:2};assert.equal(realizedGrowthWindow(history,current,5).sufficient,true);assert.equal(realizedGrowthWindow(history,{...current,size:100},5).sufficient,false);assert.equal(realizedGrowthWindow(history,{...current,defeats:1},5).measured,false);assert.equal(realizedGrowthWindow([],current,5).gain,null);});
test('collector stores latent channels and actual growth without mutating exported nested samples',()=>{const {g,p}=setup(),m=new BalanceMetrics(g,'test');g.balanceLog=m;g.buildGrid();m.observe();g.gameTime=5;p.addGrowth(500,g.balance);m.observe();const rows=m.export().groups;assert(rows.some(r=>r.realizedSamples===1&&r.realizedSuccesses===1));g.runMetrics.observe(g,1);const before=g.runMetrics.samples[0].opportunityChannels.foodGain,d=g.runMetrics.export(g);d.samples[0].opportunityChannels.foodGain=-999;assert.equal(g.runMetrics.samples[0].opportunityChannels.foodGain,before);});
