import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {SimulationRoom,roomSettings,roomBalance} from '../js/simulationRoom.js';
import {validateQuestion} from '../js/designerReview.js';
const source=JSON.parse(fs.readFileSync(new URL('../config/gameBalance.json',import.meta.url)));
function room(settings={},change=()=>{}){globalThis.window={};const c=roomSettings(settings),b=roomBalance(source,c);change(b);return new SimulationRoom(b,{width:1200,height:800,getContext:()=>({})},{keys:new Set(),mouseX:1000,mouseY:400,consumeDodge:()=>false},{showUnlock(){},showDefeatMessage(){}},{seed:c.seed,simulationRoom:true,scenario:c});}
function run(g){g.paused=false;for(let i=0;i<600&&!g.gameOver;i++)g.update(1/60);return g.export();}
test('R-META-006 isolated room contains only requested units and no ambient growth or automatic apex changes',()=>{const g=room({count:3,apex:true,targetApex:false});run(g);assert.equal(g.entities.length,4);assert.equal(g.player.apex,true);assert(g.entities.slice(1).every(e=>!e.apex));assert.equal(g.player.size,100);assert.equal(g.balance.world.wrap,false);assert.equal(g.biomeObjects.objects.length,0);assert.equal(g.balance.world.worldWidth,1800);assert.equal(source.biomes.enabled,true);});
test('R-META-006 seeded replay repeats real damage while changing only attack damage changes the result',()=>{const attack=change=>{const g=room({},change);g.input._attackQueued={angle:0,charge:.75};return run(g);};const a=attack(()=>{}),repeat=attack(()=>{}),b=attack(x=>x.combatScaling.baseAttackDamage=250);assert.deepEqual(a,repeat);assert(a.samples.at(-1).damage>0);assert(b.samples.at(-1).damage>a.samples.at(-1).damage);assert.equal(source.combatScaling.baseAttackDamage,10);});
test('R-META-006 real absorption grows the player and wounded targets finish sooner; exports cannot mutate the room',()=>{const times=[];for(const targetHp of [1,.25]){const g=room({playerColor:'blue',targetColor:'blue',playerSize:100,targetSize:90,distance:90,targetHp});g.input.absorbToggle=true;g.paused=false;while(g.entities[1].alive&&g.gameTime<10)g.update(1/60);assert(!g.entities[1].alive);assert(g.player.size>100);times.push(g.gameTime);const copy=g.export();copy.scenario.seed=42;copy.balance.world.worldWidth=42;assert.equal(g.scenario.seed,7);assert.equal(g.balance.world.worldWidth,1800);}assert(times[1]<times[0]);});
test('R-META-006 invalid room conditions are rejected before creating the experiment',()=>{for(const x of [{seed:NaN},{count:1.5},{count:99},{playerSize:1500,roomSize:800},{distance:3000},{playerColor:'unknown'},{apex:'yes'},{targetHp:0}])assert.throws(()=>roomSettings(x));});
test('R-META-007 questions require valid IDs and bounded choices while preserving plain text',()=>{assert.throws(()=>validateQuestion({title:'a'}));assert.throws(()=>validateQuestion({id:'a',title:'a',options:Array(7).fill('x')}));const q=validateQuestion({id:'a',title:'<img src=x onerror=alert(1)>',options:['빠름','느림'],revision:2});assert.equal(q.title,'<img src=x onerror=alert(1)>');assert.equal(q.revision,'2');});
test('R-META-006 AI mode executes ordinary behavior and normal/apex skill gates remain in force',()=>{const g=room({behavior:'ai',targetApex:true,distance:500});assert.equal(g.entities[1].apex,true);assert(!g.abilities.start(g.player,0,null,null,'R'));run(g);assert(g.entities[1].state||g.entities[1].specialCast);const apex=room({apex:true});assert(apex.abilities.start(apex.player,0,null,null,'R'));});
