import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';
import {AIEntity} from '../js/ai.js';
import {canAbsorb} from '../js/collision.js';
import {apexTerritoryRadius,selectedSkill} from '../js/skillCatalog.js';
import {attackChargeDurationForSize,attackTelegraphTimeForSize} from '../js/combat.js';
function setup(color='cyan'){const g=createGame(11),p=g.player;p.color=color;p.colorHex=g.balance.colors.find(c=>c.id===color).color;p.size=120;p.apex=false;p.attackState=p.dodgeState='READY';p.hp=p.maxHp=500;g.entities=[p];return {g,p};}
function cast(g,p,slot){assert(g.abilities.start(p,0,null,null,slot));for(let i=0;i<20&&p.specialCast;i++)g.abilities.update(.05);}
test('growth E unlocks without apex; R stays locked and cooldowns are independent',()=>{const {g,p}=setup();p.size=99;assert.equal(g.abilities.canCast(p,'E'),false);p.size=100;assert(g.abilities.canCast(p,'E'));assert.equal(g.abilities.canCast(p,'R'),false);cast(g,p,'E');assert(p.normalSkillCooldown>0);assert.equal(p.specialCooldown,0);p.apex=true;p._specialApex=true;assert(g.abilities.canCast(p,'R'));cast(g,p,'R');assert(p.specialCooldown>0);});
test('losing apex preserves eligible E casting but cancels R',()=>{const {g,p}=setup();p.apex=true;assert(g.abilities.start(p,0,null,null,'E'));g.abilities.loseApex(p);p.apex=false;assert.equal(p.specialCast.slot,'E');g.abilities.update(.3);assert.equal(g.abilities.specialFires,1);p.apex=true;assert(g.abilities.start(p,0,null,null,'R'));g.abilities.loseApex(p);assert.equal(p.specialCast,null);});
test('green E recruits, green R summons at most two persistent companions with no reward farming',()=>{const {g,p}=setup('green');const ally=new AIEntity({balance:g.balance,x:p.x+50,y:p.y,color:'green',colorHex:p.colorHex,startSize:50});g.entities.push(ally);cast(g,p,'E');assert.equal(ally.companionGroup,p.companionGroup);p.apex=true;p._specialApex=true;cast(g,p,'R');const summons=g.entities.filter(t=>t.summoned);assert.equal(summons.length,2);assert(summons.every(t=>t.companionGroup===p.companionGroup&&!canAbsorb(p,t)));p.specialCooldown=0;cast(g,p,'R');assert.equal(g.entities.filter(t=>t.summoned).length,2);const before=p.growth,count=g.entities.length;summons[0].alive=false;g.onEntityDeath(summons[0],p);assert.equal(p.growth,before);assert.equal(g.entities.length,count);g.gameTime=20;g.abilities.update(0);assert.equal(summons[1].alive,true);assert.equal(summons[1].summoned.absorbable,false);g.gameTime=31;g.abilities.update(0);g.allyLinks.leave(p);assert(canAbsorb(p,summons[1]));});
test('candidate change restores original concept and does not mutate an in-flight cast',()=>{const {g,p}=setup('green');p.apex=true;assert(g.abilities.start(p,0,null,null,'R'));g.balance.abilitySkills.loadout.green.R='green-morale';assert.equal(selectedSkill(g.balance,'green','R').id,'green-morale');assert.equal(p.specialCast.skill.id,'green-summon');g.abilities.update(.5);assert.equal(g.entities.filter(t=>t.summoned).length,2);p.specialCooldown=0;assert(g.abilities.start(p,0,null,null,'R'));g.abilities.update(.5);assert.equal(p.specialCooldown,11.5);g.balance.abilitySkills.loadout.green.R='cyan-freeze';assert.equal(selectedSkill(g.balance,'green','R').id,'green-summon');});
test('territory grows continuously; large-size timing is faster than the former linear curve without shrinking range',()=>{const {g,p}=setup();p.size=100;assert.equal(apexTerritoryRadius(p,g.balance),900);p.size=400;assert.equal(apexTerritoryRadius(p,g.balance),1800);const previous=structuredClone(g.balance);delete previous.combatScaling.attackTimingSoftcapSize;assert(attackChargeDurationForSize(350,g.balance)<attackChargeDurationForSize(350,previous));assert(attackTelegraphTimeForSize(600,g.balance)<attackTelegraphTimeForSize(600,previous));});
test('normal color effects damage and control enemies while leaving allies safe',()=>{for(const color of ['cyan','blue','red','yellow']){const {g,p}=setup(color),t=new AIEntity({balance:g.balance,x:p.x+100,y:p.y,color:'green',colorHex:'#0f0',startSize:40});t.hp=t.maxHp=1000;g.entities.push(t);cast(g,p,'E');if(color==='cyan'){assert(t.hp<1000);assert(t.frozen>0);}if(color==='blue'){assert(t.hp<1000);assert(t.wavePush);}if(color==='red'){assert.equal(g.abilities.embers.length,1);g.abilities.update(.5);assert(t.hp<1000);}if(color==='yellow'){assert(p.dustUntil>g.gameTime);assert.equal(t.hp,1000);}assert.equal(p.hp,500);}});
test('summon respects occupied formation capacity and losing owner title preserves summons',()=>{const {g,p}=setup('green');p.apex=true;p._specialApex=true;for(let i=0;i<4;i++){const t=new AIEntity({balance:g.balance,x:p.x+40+i*5,y:p.y,color:'green',colorHex:p.colorHex,startSize:50});g.entities.push(t);g.allyLinks.recruit(p,t);}cast(g,p,'R');const summoned=g.entities.filter(t=>t.summoned);assert.equal(summoned.length,1);assert.equal(g.allyLinks.groups.get(p.companionGroup).members.size,6);p.apex=false;g.abilities.update(0);assert.equal(summoned[0].alive,true);assert(summoned[0].companionGroup);});
