import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../tools/headless.mjs';
import {AIEntity} from '../js/ai.js';
import {selectedSkill} from '../js/skillCatalog.js';
import {defaultSkillPreset as currentDefaultSkillPreset,normalizeSkillPreset,applySkillPreset,skillPresetFromBalance,loadSavedSkillPreset} from '../js/skillPreset.js';
function defaultSkillPreset(){const p=currentDefaultSkillPreset();p.loadout.cyan={E:'cyan-chill',R:'cyan-freeze'};return p;}
function setup(color='cyan'){const g=createGame(7);g.balance.abilitySkills.loadout.cyan={E:'cyan-chill',R:'cyan-freeze'};if(color==='red')g.balance.abilitySkills.loadout.red={E:'red-vigor',R:'red-rally'};g.balance.abilitySkills.rangeReferenceSize=120;const p=g.player;p.color=color;p.size=120;p.apex=true;p._specialApex=true;p.attackState=p.dodgeState='READY';g.entities=[p];g.biomes.enabled=false;return {g,p};}
const ticks=(g,n)=>{for(let i=0;i<n;i++)g.abilities.update(1/60);};
test('preset import is transactional, rejects unknown fields/races/IDs and is independently copied',()=>{const {g}=setup(),before=JSON.stringify(g.balance),p=defaultSkillPreset();p.overrides['cyan-chill']={radius:400,cooldown:12};p.loadout.green.R='green-morale';applySkillPreset(g.balance,p);p.overrides['cyan-chill'].radius=700;assert.equal(selectedSkill(g.balance,'cyan','E').radius,400);const now=JSON.stringify(g.balance);for(const bad of [{...p,overrides:{'cyan-chill':{effect:9}}},{...p,loadout:{green:{R:'cyan-freeze'}}},{...p,settings:{unlockSize:NaN}},JSON.parse('{"format":"ball-next-skills-preset-v1","overrides":{"__proto__":{"polluted":1}}}')]){assert.throws(()=>applySkillPreset(g.balance,bad));assert.equal(JSON.stringify(g.balance),now);}assert.notEqual(before,now);});
test('R frost real reach, windup and damage follow cast snapshot despite mid-cast edits',()=>{const {g,p}=setup(),t=new AIEntity({balance:g.balance,x:p.x+350,y:p.y,color:'red',colorHex:'#f00',startSize:40});t.hp=t.maxHp=1000;g.entities.push(t);g.balance.abilitySkills.overrides={'cyan-freeze':{radius:400,damage:1,windup:.2,freezeSeconds:.5}};assert(g.abilities.start(p,0));g.balance.abilitySkills.overrides['cyan-freeze'].radius=80;ticks(g,12);assert.equal(t.hp,890);assert(t.frozen>0);assert.equal(g.abilities.metrics.export().rows[0].settings.radius,400);});
test('blue wave length and width control actual hits and persist after tuning changes',()=>{const {g,p}=setup('blue'),t=new AIEntity({balance:g.balance,x:p.x+500,y:p.y+110,color:'red',colorHex:'#f00',startSize:40});t.hp=t.maxHp=1000;g.entities.push(t);g.balance.abilitySkills.overrides={'blue-trident':{length:600,width:240}};g.abilities.start(p,0);p.specialCast.directions=[0];ticks(g,36);g.balance.abilitySkills.overrides['blue-trident']={length:100,width:20};ticks(g,30);assert(t.hp<1000);});
test('yellow actual field radius, duration and tick HP fraction follow preset',()=>{const {g,p}=setup('yellow'),t=new AIEntity({balance:g.balance,x:p.x+500,y:p.y,color:'red',colorHex:'#f00',startSize:40});t.hp=t.maxHp=1000;g.entities.push(t);g.balance.abilitySkills.overrides={'yellow-storm':{radius:600,castRange:80,hpFraction:.1,fieldDuration:1}};g.abilities.start(p,0,{x:p.x,y:p.y});ticks(g,48);assert(g.abilities.fields[0].radius===600);ticks(g,15);assert.equal(t.hp,920);ticks(g,45);assert.equal(g.abilities.fields.length,0);});
test('configured rally and E vigor change real speed/damage buffs',()=>{const {g,p}=setup('red'),t=new AIEntity({balance:g.balance,x:p.x+100,y:p.y,color:'blue',colorHex:'#00f',startSize:40});g.entities.push(t);g.balance.abilitySkills.overrides={'red-vigor':{buffSpeed:1.4,buffDamage:.4},'red-rally':{buffSpeed:1.5,buffDamage:.6}};g.abilities.start(p,0,null,null,'E');ticks(g,15);assert.equal(g.abilities.speedMultiplier(p),1.4);assert.equal(g.abilities.damageMultiplier(p),1.4);g.abilities.start(p,0,{x:t.x,y:t.y},t,'R');ticks(g,48);assert.equal(g.abilities.speedMultiplier(p),1.5);assert.equal(g.abilities.damageMultiplier(p),2);});
test('summon cap, size limits and absorption delay are configurable without providing growth rewards',()=>{const {g,p}=setup('green');g.balance.abilitySkills.overrides={'green-summon':{summonCount:1,summonAbsorbDelay:3,summonSizeFraction:.15,summonSizeVariation:0,summonSizeCapFraction:.2}};g.abilities.start(p,0);ticks(g,30);const summoned=g.entities.filter(t=>t.summoned);assert.equal(summoned.length,1);assert.equal(summoned[0].size,p.size*.15);g.gameTime=4;g.abilities.update(0);assert.equal(summoned[0].alive,true);assert.equal(summoned[0].summoned.absorbable,true);});
test('autoplay respects attack reach while green E remains useful without recipients',()=>{const {g,p}=setup(),t=new AIEntity({balance:g.balance,x:p.x+300,y:p.y,color:'red',colorHex:'#f00',startSize:50});g.entities.push(t);p.specialCooldown=10;g.buildGrid();g.autoplay.setEnabled(true);g.autoplay.update(.1);assert.equal(g.autoplay.action.special,false);t.x=p.x+100;g.buildGrid();g.autoplay.update(.1);assert.equal(g.autoplay.action.skillSlot,'E');p.color='green';assert.equal(g.abilities.canAffect(p,t,'E'),true);});
test('saved settings recover safely and mixed runtime tuning is marked in metrics',()=>{const {g,p}=setup();const packet=defaultSkillPreset();packet.settings.unlockSize=180;assert.equal(loadSavedSkillPreset(g.balance,{getItem:()=>JSON.stringify(packet)}),null);assert.equal(g.balance.abilitySkills.unlockSize,180);const before=JSON.stringify(g.balance);assert.match(loadSavedSkillPreset(g.balance,{getItem:()=>'{'}),/불러오지/);assert.equal(JSON.stringify(g.balance),before);g.abilities.start(p,0,null,null,'E');ticks(g,15);p.normalSkillCooldown=0;g.balance.abilitySkills.overrides={'cyan-chill':{radius:400}};g.abilities.start(p,0,null,null,'E');ticks(g,15);const d=g.abilities.metrics.export();assert.equal(d.mixedConfiguration,true);d.rows[0].settings.radius=0;assert.equal(g.abilities.metrics.export().rows[0].settings.radius,200);assert.equal(skillPresetFromBalance(g.balance).overrides['cyan-chill'].radius,400);});
