import fs from 'node:fs';import {pathToFileURL} from 'node:url';import {createGame} from './headless.mjs';import {AIEntity,updateAI} from '../js/ai.js';import {updateAttackStack,updateDodgeStack,updateHealthRegen,updateKnockback} from '../js/combat.js';
export const COLORS=['cyan','blue','green','red','yellow'];
export function duel({seed=7,size=400,colors=['cyan','red'],reverse=false,seconds=90,overrides={},war=false,disabledSkillSide=null}={}){
 const g=createGame(seed);g.balance.abilitySkills.overrides={...g.balance.abilitySkills.overrides,...overrides};g.biomes.enabled=false;g.era.enabled=false;g.era.warDecision=()=>false;g.era.warDestination=()=>null;g.relics.enabled=false;
 const fighters=colors.map((color,i)=>new AIEntity({balance:g.balance,x:4000+(i?1:-1)*(size*.7+140),y:4000,color,colorHex:'#fff',startSize:size}));
 for(const e of fighters){e.apex=e._specialApex=true;e.moveSpeed=g.balance.ai.movementSpeed;e.personality='opportunist';e.role='predator';e.companionAffinity='neutral';}
 if(reverse){[fighters[0].x,fighters[1].x]=[fighters[1].x,fighters[0].x];}g.entities=[...fighters];if(war){g.era.enabled=true;g.era.phase={id:'war'};delete g.era.warDecision;for(let i=0;i<2;i++)fighters[i].warTargets=new Set([fighters[1-i]]);}if(disabledSkillSide!==null){const canCast=g.abilities.canCast.bind(g.abilities);g.abilities.canCast=(e,slot)=>e!==fighters[disabledSkillSide]&&canCast(e,slot);}g.player.alive=false;let elapsed=0;
 for(let tick=0;tick<seconds*30&&fighters.every(e=>e.alive);tick++){const dt=1/30;g.gameTime=elapsed=(tick+1)*dt;g.buildGrid();g.allyLinks.update(dt);g.abilities.update(dt);
  const actors=g.entities.filter(e=>e.alive&&e.behavior==='ai');if(tick%2)actors.reverse();for(const e of actors){g.abilities.considerAI(e);updateAI(e,dt,g,g.balance);updateKnockback(e,dt);updateHealthRegen(e,dt,g.balance);updateAttackStack(e,dt,g.balance.ai.attackCooldown);updateDodgeStack(e,dt,g.balance);}g.resolvePushApart(dt);
 }
 const winner=fighters[0].alive!==fighters[1].alive?+(fighters[1].alive):null;
 return {seed,size,colors,reverse,war,disabledSkillSide,seconds:elapsed,winner,hp: fighters.map(e=>Math.max(0,e.hp/e.maxHp)),summons:g.entities.filter(e=>e.summoned).length,skills:g.abilities.metrics.export().rows};
}
export function summarize(rows){const matches=[];for(const size of [...new Set(rows.map(r=>r.size))])for(let i=0;i<COLORS.length;i++)for(let j=i+1;j<COLORS.length;j++){const colors=[COLORS[i],COLORS[j]],sample=rows.filter(r=>r.size===size&&r.colors.join()===colors.join()),wins=sample.filter(r=>r.winner===0).length,losses=sample.filter(r=>r.winner===1).length,draws=sample.length-wins-losses;matches.push({size,colors,n:sample.length,wins,losses,draws,score:sample.length?(wins+draws*.5)/sample.length:0,decisiveWinRate:wins+losses?wins/(wins+losses):null,meanSeconds:sample.reduce((s,r)=>s+r.seconds,0)/sample.length});}const overall=COLORS.map(color=>{let wins=0,losses=0,draws=0;for(const r of rows){const side=r.colors.indexOf(color);if(side<0)continue;if(r.winner===null)draws++;else if(r.winner===side)wins++;else losses++;}const n=wins+losses+draws;return {color,n,wins,losses,draws,score:n?(wins+draws*.5)/n:null};});return {matches,overall};}
export function sweep({seeds=[7,23,71,101],sizes=[200,400,800],overrides={},war=false}={}){const rows=[];for(const size of sizes)for(let i=0;i<5;i++)for(let j=i+1;j<5;j++)for(const seed of seeds)for(const reverse of [false,true])rows.push(duel({size,seed,colors:[COLORS[i],COLORS[j]],reverse,overrides,war}));return {protocol:{war,dt:1/30,seconds:90,seeds,sizes,policy:'native opportunist AI (war flag enables persistent war targets); identical speed and size; mirrored starts; alternating update order; flat world; skill summons allowed, no external allies; draw is timeout or double defeat'},overrides,...summarize(rows),rows};}
if(import.meta.url===pathToFileURL(process.argv[1]).href){const args=process.argv.slice(2),war=args.includes('--war'),pos=args.filter(x=>x!=='--war'),output=pos[0]??'reports/duels.json',overrides=pos[1]?JSON.parse(fs.readFileSync(pos[1])):{};const data=sweep({overrides,war});fs.writeFileSync(output,JSON.stringify(data,null,2));console.log(JSON.stringify(data.overall));}
